/*
###############################################################
#  Generated by:      Cadence Innovus 19.10-p002_1
#  OS:                Linux x86_64(Host ID cadpc15)
#  Generated on:      Sat Apr  9 14:55:03 2022
#  Design:            PE
#  Command:           saveNetlist -phys -excludeLeafCell -excludeCellInst {FILL1TS FILL2TS FILL4TS FILL8TS FILL16TS FILL32TS FILL64TS} PE.phy.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : O-2018.06-SP5-1
// Date      : Thu Apr  7 18:45:46 2022
/////////////////////////////////////////////////////////////
module PE (
	clk, 
	rst_n, 
	fire_in, 
	weight_in, 
	data_in, 
	fire_out, 
	weight_out, 
	data_out, 
	result);
   input clk;
   input rst_n;
   input fire_in;
   input [7:0] weight_in;
   input [7:0] data_in;
   output fire_out;
   output [7:0] weight_out;
   output [7:0] data_out;
   output [31:0] result;

   // Internal wires
   wire FE_PSN287_n222;
   wire FE_PSN286_n544;
   wire FE_PSN285_n565;
   wire FE_PSN284_FE_OFN25_data_in_6;
   wire FE_PSN283_n110;
   wire FE_PSN281_n205;
   wire FE_PSN280_n555;
   wire FE_PDN279_weight_in_3;
   wire FE_PDN278_data_in_6;
   wire FE_OCPN178_FE_OFN30_data_in_3;
   wire FE_RN_105_0;
   wire FE_RN_104_0;
   wire FE_RN_103_0;
   wire FE_RN_12;
   wire FE_RN_11;
   wire FE_RN_102_0;
   wire FE_RN_101_0;
   wire FE_RN_100_0;
   wire FE_RN_99_0;
   wire FE_RN_98_0;
   wire FE_RN_10;
   wire FE_OCPN271_n255;
   wire FE_RN_97_0;
   wire FE_OCPN177_weight_in_3;
   wire FE_RN_9;
   wire FE_RN_95_0;
   wire FE_RN_94_0;
   wire FE_RN_93_0;
   wire FE_RN_92_0;
   wire FE_RN_91_0;
   wire FE_RN_90_0;
   wire FE_RN_89_0;
   wire FE_RN_88_0;
   wire FE_RN_87_0;
   wire FE_RN_86_0;
   wire FE_RN_85_0;
   wire FE_RN_84_0;
   wire FE_RN_83_0;
   wire FE_RN_82_0;
   wire FE_RN_81_0;
   wire FE_RN_78_0;
   wire FE_RN_77_0;
   wire FE_RN_76_0;
   wire FE_RN_75_0;
   wire FE_RN_74_0;
   wire FE_RN_73_0;
   wire FE_RN_72_0;
   wire FE_RN_71_0;
   wire FE_RN_70_0;
   wire FE_RN_8;
   wire FE_RN_68_0;
   wire FE_RN_67_0;
   wire FE_RN_66_0;
   wire FE_RN_65_0;
   wire FE_RN_64_0;
   wire FE_RN_63_0;
   wire FE_RN_62_0;
   wire FE_RN_60_0;
   wire FE_RN_59_0;
   wire FE_RN_58_0;
   wire FE_RN_57_0;
   wire FE_RN_56_0;
   wire FE_RN_55_0;
   wire FE_RN_54_0;
   wire FE_RN_53_0;
   wire FE_RN_52_0;
   wire FE_RN_47_0;
   wire FE_RN_46_0;
   wire FE_RN_45_0;
   wire FE_RN_44_0;
   wire FE_RN_43_0;
   wire FE_RN_42_0;
   wire FE_RN_41_0;
   wire FE_RN_7;
   wire FE_RN_6;
   wire FE_RN_5;
   wire FE_RN_4;
   wire FE_RN_3;
   wire FE_RN_40_0;
   wire FE_RN_39_0;
   wire FE_RN_38_0;
   wire FE_RN_37_0;
   wire FE_RN_36_0;
   wire FE_RN_2;
   wire FE_RN_35_0;
   wire FE_RN_1;
   wire FE_OCPN175_n294;
   wire FE_OCPN174_n294;
   wire FE_OCPN173_n128;
   wire FE_OCPN170_n236;
   wire FE_RN_26_0;
   wire FE_RN_25_0;
   wire FE_RN_24_0;
   wire FE_RN_23_0;
   wire FE_RN_22_0;
   wire FE_RN_20_0;
   wire FE_RN_17_0;
   wire FE_RN_16_0;
   wire FE_RN_14_0;
   wire FE_RN_13_0;
   wire FE_RN_12_0;
   wire FE_RN_11_0;
   wire FE_RN_10_0;
   wire FE_RN_9_0;
   wire FE_RN_8_0;
   wire FE_RN_7_0;
   wire FE_RN_6_0;
   wire FE_RN_5_0;
   wire FE_RN_4_0;
   wire FE_RN_3_0;
   wire FE_RN_2_0;
   wire FE_RN_1_0;
   wire FE_RN_0_0;
   wire FE_OCPN169_n294;
   wire FE_OFN262_n294;
   wire FE_OFN261_data_in_2;
   wire FE_OFN260_data_in_4;
   wire FE_OFN259_weight_in_5;
   wire FE_OFN258_FE_DBTN0_n34;
   wire FE_OFN257_n294;
   wire FE_OFN256_n279;
   wire FE_OFN255_weight_in_7;
   wire FE_OFN168_n108;
   wire FE_OFN251_weight_in_3;
   wire FE_OFN250_data_in_0;
   wire FE_OFN249_n156;
   wire FE_OFN248_n294;
   wire FE_OFN247_weight_in_5;
   wire FE_OFN167_n;
   wire FE_OFN166_n;
   wire FE_OFN165_n;
   wire FE_OFN246_data_in_5;
   wire FE_OFN245_data_in_0;
   wire FE_OFN244_weight_in_1;
   wire FE_OFN243_weight_in_6;
   wire FE_OFN242_data_in_7;
   wire FE_OFN240_weight_in_7;
   wire FE_OFN239_fire_in;
   wire FE_OFN238_weight_in_4;
   wire FE_OFN236_weight_in_3;
   wire FE_OFN235_weight_in_5;
   wire FE_OFN163_n294;
   wire FE_OFN161_n108;
   wire FE_OFN159_n;
   wire FE_OFN158_rst_n;
   wire FE_OFN157_data_in_0;
   wire FE_OFN156_data_in_1;
   wire FE_OFN150_data_in_7;
   wire FE_OFN149_weight_in_0;
   wire FE_OFN142_weight_in_7;
   wire FE_OFN141_n279;
   wire FE_OFN139_n226;
   wire FE_OFN138_n226;
   wire FE_OFN131_n156;
   wire FE_OFN130_n156;
   wire FE_OFN129_n108;
   wire FE_OFN125_n102;
   wire FE_OFN124_n102;
   wire FE_OFN123_n102;
   wire FE_OFN122_FE_DBTN1_fire_in;
   wire FE_OFN121_FE_DBTN1_fire_in;
   wire FE_OFN120_FE_DBTN1_fire_in;
   wire FE_OFN119_FE_DBTN1_fire_in;
   wire FE_OFN118_FE_DBTN1_fire_in;
   wire FE_OFN117_FE_DBTN1_fire_in;
   wire FE_OFN116_FE_DBTN1_fire_in;
   wire FE_OFN115_FE_DBTN1_fire_in;
   wire FE_OFN114_FE_DBTN1_fire_in;
   wire FE_OFN113_FE_DBTN1_fire_in;
   wire FE_OFN112_FE_DBTN1_fire_in;
   wire FE_OFN111_FE_DBTN1_fire_in;
   wire FE_OFN110_FE_DBTN1_fire_in;
   wire FE_OFN109_FE_DBTN1_fire_in;
   wire FE_OFN108_FE_DBTN1_fire_in;
   wire FE_OFN107_FE_DBTN1_fire_in;
   wire FE_OFN106_FE_DBTN1_fire_in;
   wire FE_OFN105_FE_DBTN1_fire_in;
   wire FE_OFN104_FE_DBTN1_fire_in;
   wire FE_OFN103_FE_DBTN1_fire_in;
   wire FE_OFN102_FE_DBTN1_fire_in;
   wire FE_OFN101_FE_DBTN1_fire_in;
   wire FE_OFN100_FE_DBTN1_fire_in;
   wire FE_OFN99_FE_DBTN1_fire_in;
   wire FE_OFN98_FE_DBTN1_fire_in;
   wire FE_OFN97_FE_DBTN1_fire_in;
   wire FE_OFN92_n294;
   wire FE_OFN89_fire_in;
   wire FE_OFN88_fire_in;
   wire FE_OFN87_fire_in;
   wire FE_OFN86_fire_in;
   wire FE_OFN85_fire_in;
   wire FE_OFN84_fire_in;
   wire FE_OFN83_fire_in;
   wire FE_OFN82_fire_in;
   wire FE_OFN81_fire_in;
   wire FE_OFN80_fire_in;
   wire FE_OFN79_fire_in;
   wire FE_OFN78_fire_in;
   wire FE_OFN77_fire_in;
   wire FE_OFN75_rst_n;
   wire FE_OFN74_rst_n;
   wire FE_OFN73_rst_n;
   wire FE_OFN72_rst_n;
   wire FE_OFN71_rst_n;
   wire FE_OFN70_rst_n;
   wire FE_OFN69_rst_n;
   wire FE_OFN68_rst_n;
   wire FE_OFN67_rst_n;
   wire FE_OFN66_rst_n;
   wire FE_OFN65_rst_n;
   wire FE_OFN64_rst_n;
   wire FE_OFN63_rst_n;
   wire FE_OFN62_rst_n;
   wire FE_OFN61_rst_n;
   wire FE_OFN60_rst_n;
   wire FE_OFN59_rst_n;
   wire FE_OFN58_rst_n;
   wire FE_OFN57_rst_n;
   wire FE_OFN56_rst_n;
   wire FE_OFN55_rst_n;
   wire FE_OFN54_rst_n;
   wire FE_OFN53_rst_n;
   wire FE_OFN52_rst_n;
   wire FE_OFN51_rst_n;
   wire FE_OFN50_rst_n;
   wire FE_OFN49_rst_n;
   wire FE_OFN48_rst_n;
   wire FE_OFN47_rst_n;
   wire FE_OFN46_rst_n;
   wire FE_OFN45_rst_n;
   wire FE_OFN44_rst_n;
   wire FE_OFN43_rst_n;
   wire FE_OFN41_data_out_0;
   wire FE_OFN39_data_in_0;
   wire FE_OFN35_data_in_1;
   wire FE_OFN33_data_in_2;
   wire FE_OFN30_data_in_3;
   wire FE_OFN28_data_in_4;
   wire FE_OFN27_data_in_5;
   wire FE_OFN25_data_in_6;
   wire FE_OFN19_weight_in_1;
   wire FE_OFN17_weight_in_1;
   wire FE_OFN16_weight_in_1;
   wire FE_OFN15_weight_in_2;
   wire FE_OFN12_weight_in_3;
   wire FE_OFN11_weight_in_3;
   wire FE_OFN10_weight_in_3;
   wire FE_OFN9_weight_in_4;
   wire FE_OFN6_weight_in_5;
   wire FE_DBTN2_weight_in_5;
   wire FE_DBTN1_fire_in;
   wire FE_DBTN0_n34;
   wire VSS;
   wire VDD;
   wire N37;
   wire N38;
   wire N39;
   wire N40;
   wire N41;
   wire N42;
   wire N43;
   wire N44;
   wire N45;
   wire N46;
   wire N47;
   wire N48;
   wire N49;
   wire N50;
   wire N51;
   wire N52;
   wire N53;
   wire N54;
   wire N55;
   wire N56;
   wire N57;
   wire N58;
   wire N59;
   wire N60;
   wire N61;
   wire N62;
   wire N63;
   wire N64;
   wire N65;
   wire N66;
   wire N67;
   wire N68;
   wire n35;
   wire n74;
   wire n75;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n115;
   wire n116;
   wire n117;
   wire n119;
   wire n121;
   wire n122;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n160;
   wire n161;
   wire n162;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n226;
   wire n228;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n275;
   wire n276;
   wire n277;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n291;
   wire n292;
   wire n293;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n3701;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n3901;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n4001;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n4101;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n4201;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n4301;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n437;
   wire n438;
   wire n439;
   wire n4401;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n447;
   wire n448;
   wire n449;
   wire n4501;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n458;
   wire n459;
   wire n4601;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n4701;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n477;
   wire n478;
   wire n479;
   wire n4801;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n487;
   wire n488;
   wire n489;
   wire n4901;
   wire n491;
   wire n492;
   wire n493;
   wire n494;
   wire n495;
   wire n497;
   wire n526;
   wire n527;
   wire n528;
   wire n5301;
   wire n531;
   wire n532;
   wire n533;
   wire n534;
   wire n535;
   wire n536;
   wire n537;
   wire n538;
   wire n539;
   wire n5401;
   wire n543;
   wire n544;
   wire n545;
   wire n546;
   wire n547;
   wire n548;
   wire n549;
   wire n5501;
   wire n551;
   wire n552;
   wire n553;
   wire n554;
   wire n555;
   wire n556;
   wire n557;
   wire n558;
   wire n559;
   wire n5601;
   wire n562;
   wire n563;
   wire n564;
   wire n565;
   wire n566;
   wire n567;
   wire n568;
   wire n569;
   wire n5701;
   wire n571;
   wire n572;
   wire n573;
   wire n574;
   wire n575;
   wire n576;
   wire n577;
   wire n578;
   wire n579;
   wire n5801;
   wire n581;
   wire n582;
   wire n583;
   wire n584;
   wire n585;
   wire n587;
   wire n588;
   wire n589;
   wire n5901;
   wire n591;
   wire n592;
   wire n594;
   wire n595;
   wire n596;
   wire n597;
   wire n598;
   wire n599;
   wire n6001;
   wire n601;
   wire n602;
   wire n603;
   wire n604;
   wire n605;
   wire n606;
   wire n607;
   wire n609;
   wire n613;
   wire n614;
   wire n615;
   wire n616;
   wire n617;
   wire n618;
   wire n619;
   wire n6201;
   wire n621;
   wire n622;
   wire n623;
   wire n624;
   wire n625;
   wire n626;
   wire n627;
   wire n628;
   wire n629;
   wire n6301;
   wire n631;
   wire n632;
   wire n633;
   wire n634;
   wire n635;
   wire n636;
   wire n637;
   wire n638;
   wire n639;
   wire n6401;
   wire n641;
   wire n642;
   wire n643;
   wire n644;
   wire [31:0] tmp;

   // Module instantiations
   BUFX6TS FE_PSC287_n222 (
	.A(n222),
	.Y(FE_PSN287_n222), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_PSC286_n544 (
	.A(n544),
	.Y(FE_PSN286_n544), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_PSC285_n565 (
	.A(n565),
	.Y(FE_PSN285_n565), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX4TS FE_PSC284_FE_OFN25_data_in_6 (
	.A(FE_OFN25_data_in_6),
	.Y(FE_PSN284_FE_OFN25_data_in_6), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_PSC283_n110 (
	.A(n110),
	.Y(FE_PSN283_n110), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX6TS FE_PSC281_n205 (
	.A(n205),
	.Y(FE_PSN281_n205), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_PSC280_n555 (
	.A(n555),
	.Y(FE_PSN280_n555), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX2TS FE_PDC279_weight_in_3 (
	.A(weight_in[3]),
	.Y(FE_PDN279_weight_in_3), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_PDC278_data_in_6 (
	.A(data_in[6]),
	.Y(FE_PDN278_data_in_6), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX4TS FE_OCPC278_FE_OFN30_data_in_3 (
	.A(FE_OFN30_data_in_3),
	.Y(FE_OCPN178_FE_OFN30_data_in_3), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS FE_RC_218_0 (
	.A(FE_OFN159_n),
	.B(FE_OFN246_data_in_5),
	.Y(n228), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS FE_RC_217_0 (
	.A(FE_OFN33_data_in_2),
	.B(FE_OFN166_n),
	.Y(n207), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS FE_RC_216_0 (
	.A0(FE_OFN163_n294),
	.A1(n396),
	.B0(n395),
	.Y(n398), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_215_0 (
	.A(n356),
	.Y(FE_RN_105_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI2BB1X2TS FE_RC_214_0 (
	.A0N(n4701),
	.A1N(n473),
	.B0(FE_RN_105_0),
	.Y(n358), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X2TS FE_RC_213_0 (
	.A0(n536),
	.A1(n553),
	.B0(n535),
	.Y(n5401), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI2BB1X2TS FE_RC_212_0 (
	.A0N(FE_OFN130_n156),
	.A1N(FE_OFN138_n226),
	.B0(FE_RN_84_0),
	.Y(n241), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_211_0 (
	.A(n127),
	.B(n128),
	.Y(FE_RN_2_0), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS FE_RC_210_0 (
	.A(FE_OCPN177_weight_in_3),
	.B(FE_OFN9_weight_in_4),
	.Y(FE_RN_9), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X2TS FE_RC_209_0 (
	.A0(n415),
	.A1(n414),
	.B0(n413),
	.Y(n416), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS FE_RC_208_0 (
	.A0(n567),
	.A1(n563),
	.B0(FE_PSN285_n565),
	.Y(n5601), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS FE_RC_207_0 (
	.A0(n359),
	.A1(FE_OCPN169_n294),
	.B0(n358),
	.Y(FE_RN_104_0), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_206_0 (
	.A(FE_RN_104_0),
	.B(n93),
	.Y(n364), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS FE_RC_205_0 (
	.A(n150),
	.B(n151),
	.Y(FE_RN_103_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS FE_RC_204_0 (
	.A(FE_RN_24_0),
	.B(FE_RN_103_0),
	.Y(n185), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U413_dup (
	.A(FE_OCPN177_weight_in_3),
	.B(FE_OFN30_data_in_3),
	.Y(FE_RN_12), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS FE_RC_124_0_dup (
	.A(FE_OFN17_weight_in_1),
	.B(FE_OFN149_weight_in_0),
	.Y(FE_RN_11), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS FE_RC_203_0 (
	.A(FE_OFN247_weight_in_5),
	.B(FE_OFN35_data_in_1),
	.Y(n130), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX2TS FE_RC_202_0 (
	.A(n161),
	.Y(FE_RN_102_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX4TS FE_RC_201_0 (
	.AN(n160),
	.B(FE_RN_102_0),
	.Y(n596), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS FE_RC_200_0 (
	.AN(FE_RN_63_0),
	.B(FE_OFN121_FE_DBTN1_fire_in),
	.Y(FE_RN_101_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX2TS FE_RC_199_0 (
	.AN(FE_RN_101_0),
	.B(FE_RN_85_0),
	.Y(FE_RN_86_0), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_198_0 (
	.A(FE_RN_100_0),
	.Y(n131), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_197_0 (
	.A(FE_OFN39_data_in_0),
	.B(FE_OFN259_weight_in_5),
	.Y(FE_RN_100_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX4TS FE_RC_196_0 (
	.AN(FE_OFN9_weight_in_4),
	.B(FE_OFN12_weight_in_3),
	.Y(FE_RN_98_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX4TS FE_RC_195_0 (
	.AN(FE_OFN12_weight_in_3),
	.B(FE_OFN9_weight_in_4),
	.Y(FE_RN_99_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X6TS FE_RC_194_0 (
	.A(FE_RN_99_0),
	.B(FE_RN_98_0),
	.Y(FE_RN_37_0), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS FE_RC_192_0 (
	.A(FE_OFN159_n),
	.B(FE_OFN242_data_in_7),
	.Y(n251), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC191_data_in_6_dup (
	.A(FE_PDN278_data_in_6),
	.Y(FE_RN_10), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX6TS FE_OCPC271_n255 (
	.A(n255),
	.Y(FE_OCPN271_n255), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX3TS FE_RC_191_0 (
	.A(n301),
	.Y(FE_RN_97_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS FE_RC_190_0 (
	.A(FE_RN_97_0),
	.B(n300),
	.Y(FE_RN_74_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X2TS FE_RC_189_0 (
	.A0(FE_OFN258_FE_DBTN0_n34),
	.A1(FE_OFN157_data_in_0),
	.B0(FE_OFN149_weight_in_0),
	.B1(n157),
	.Y(n158), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS FE_RC_188_0 (
	.A(FE_OFN27_data_in_5),
	.B(FE_OFN142_weight_in_7),
	.Y(n254), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX8TS FE_OCPC277_weight_in_3 (
	.A(FE_OFN251_weight_in_3),
	.Y(FE_OCPN177_weight_in_3), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX8TS FE_OCPC276_weight_in_3 (
	.A(FE_OFN251_weight_in_3),
	.Y(FE_OFN11_weight_in_3), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX6TS FE_OCPC274_weight_in_3 (
	.A(FE_OFN10_weight_in_3),
	.Y(FE_OFN251_weight_in_3), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX4TS FE_OCPC273_weight_in_3 (
	.A(FE_OFN10_weight_in_3),
	.Y(FE_OFN236_weight_in_3), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX6TS FE_OCPC272_weight_in_3 (
	.A(FE_OFN10_weight_in_3),
	.Y(FE_OFN12_weight_in_3), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX8TS FE_OCPC271_weight_in_3 (
	.A(FE_PDN279_weight_in_3),
	.Y(FE_OFN10_weight_in_3), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X1TS FE_RC_187_0 (
	.A0(n147),
	.A1(FE_OFN258_FE_DBTN0_n34),
	.B0(n132),
	.B1(FE_OFN149_weight_in_0),
	.Y(n144), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS FE_RC_184_0 (
	.A(FE_OFN11_weight_in_3),
	.B(FE_OFN25_data_in_6),
	.Y(n206), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS FE_RC_183_0 (
	.A(FE_OFN236_weight_in_3),
	.B(FE_OFN15_weight_in_2),
	.Y(n98), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS FE_RC_182_0 (
	.A(FE_OFN17_weight_in_1),
	.B(FE_OFN261_data_in_2),
	.Y(n168), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X1TS FE_RC_181_0 (
	.A0(n268),
	.A1(FE_OFN141_n279),
	.B0(n277),
	.B1(FE_OFN129_n108),
	.Y(n276), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X2TS FE_RC_180_0 (
	.A0(n74),
	.A1(n204),
	.B0(FE_OFN123_n102),
	.B1(n228),
	.Y(n222), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS FE_RC_179_0 (
	.A0(FE_OFN92_n294),
	.A1(n465),
	.B0(n464),
	.Y(n468), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX1TS FE_RC_178_0 (
	.AN(FE_OFN111_FE_DBTN1_fire_in),
	.B(FE_RN_41_0),
	.Y(FE_RN_94_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND3BX2TS FE_RC_177_0 (
	.AN(FE_RN_94_0),
	.B(FE_RN_45_0),
	.C(FE_RN_43_0),
	.Y(FE_RN_95_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX2TS FE_RC_176_0 (
	.AN(FE_RN_47_0),
	.B(FE_RN_95_0),
	.Y(N60), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX4TS FE_RC_175_0 (
	.A(FE_OFN131_n156),
	.Y(FE_RN_91_0), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_174_0 (
	.A(FE_RN_12),
	.Y(FE_RN_92_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_173_0 (
	.A(FE_RN_92_0),
	.B(FE_RN_91_0),
	.Y(FE_RN_93_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X4TS FE_RC_172_0 (
	.A0(FE_OFN139_n226),
	.A1(n143),
	.B0(FE_RN_93_0),
	.Y(n146), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS FE_RC_171_0 (
	.A(FE_OFN17_weight_in_1),
	.B(FE_OCPN178_FE_OFN30_data_in_3),
	.Y(n167), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS FE_RC_170_0 (
	.A(FE_OFN19_weight_in_1),
	.B(FE_OFN35_data_in_1),
	.Y(n157), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS FE_RC_169_0 (
	.A0(FE_OFN92_n294),
	.A1(n453),
	.B0(n452),
	.Y(n456), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS FE_RC_168_0 (
	.AN(n88),
	.B(FE_OFN112_FE_DBTN1_fire_in),
	.Y(FE_RN_88_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_167_0 (
	.A(n445),
	.B(FE_RN_88_0),
	.Y(FE_RN_89_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X2TS FE_RC_166_0 (
	.A(FE_OFN112_FE_DBTN1_fire_in),
	.B(n88),
	.Y(FE_RN_90_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X2TS FE_RC_165_0 (
	.A0(n445),
	.A1(FE_RN_90_0),
	.B0(FE_RN_89_0),
	.Y(N58), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_164_0 (
	.A(FE_RN_64_0),
	.Y(FE_RN_85_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_162_0 (
	.A(FE_RN_66_0),
	.B(FE_RN_86_0),
	.Y(FE_RN_87_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX2TS FE_RC_161_0 (
	.AN(FE_RN_68_0),
	.B(FE_RN_87_0),
	.Y(N66), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS FE_RC_160_0 (
	.A0(FE_OCPN169_n294),
	.A1(n471),
	.B0(n4701),
	.Y(n475), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS FE_RC_159_0 (
	.A(FE_OFN15_weight_in_2),
	.B(FE_OFN16_weight_in_1),
	.Y(n156), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X4TS FE_RC_158_0 (
	.A0(n287),
	.A1(n532),
	.B0(n286),
	.Y(n288), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_157_0 (
	.A(n224),
	.Y(FE_RN_84_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X2TS FE_RC_155_0 (
	.A0(n268),
	.A1(FE_OFN129_n108),
	.B0(FE_OFN141_n279),
	.B1(n254),
	.Y(n269), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX6TS FE_RC_154_0 (
	.A(FE_RN_37_0),
	.Y(FE_RN_83_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X6TS FE_RC_153_0 (
	.A(FE_RN_83_0),
	.B(n101),
	.Y(n75), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_152_0 (
	.A(n119),
	.B(n122),
	.Y(FE_RN_62_0), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS FE_RC_151_0 (
	.A(n273),
	.B(n272),
	.Y(FE_RN_77_0), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX8TS FE_RC_150_0 (
	.A(FE_RN_82_0),
	.Y(n101), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_149_0 (
	.A(FE_OFN6_weight_in_5),
	.B(FE_OFN9_weight_in_4),
	.Y(FE_RN_82_0), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS FE_RC_148_0 (
	.A(n212),
	.B(n213),
	.Y(FE_RN_81_0), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS FE_RC_147_0 (
	.A(FE_RN_81_0),
	.B(n208),
	.Y(n195), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS FE_RC_141_0 (
	.A(FE_OFN255_weight_in_7),
	.B(FE_OFN150_data_in_7),
	.Y(n277), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_140_0 (
	.A(FE_RN_78_0),
	.Y(n268), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_139_0 (
	.A(FE_OFN255_weight_in_7),
	.B(FE_PSN284_FE_OFN25_data_in_6),
	.Y(FE_RN_78_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS FE_RC_137_0 (
	.A(FE_RN_77_0),
	.B(FE_OFN105_FE_DBTN1_fire_in),
	.Y(N50), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_135_0 (
	.A(n300),
	.Y(FE_RN_75_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_134_0 (
	.A(n301),
	.B(FE_RN_75_0),
	.Y(FE_RN_76_0), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS FE_RC_133_0 (
	.A0(FE_RN_74_0),
	.A1(FE_RN_76_0),
	.B0(FE_OFN97_FE_DBTN1_fire_in),
	.Y(N53), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_132_0 (
	.A(FE_RN_2_0),
	.B(tmp[6]),
	.Y(n141), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_131_0 (
	.A(FE_OFN243_weight_in_6),
	.B(FE_DBTN2_weight_in_5),
	.Y(n108), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_130_0 (
	.A(FE_RN_9_0),
	.B(tmp[10]),
	.Y(n240), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_129_0 (
	.A(FE_RN_62_0),
	.Y(FE_RN_73_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI2BB1X4TS FE_RC_128_0 (
	.A0N(FE_RN_73_0),
	.A1N(n121),
	.B0(FE_RN_60_0),
	.Y(n137), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_RC_127_0 (
	.A(n279),
	.Y(FE_OFN256_n279), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX6TS FE_RC_126_0 (
	.A(n279),
	.Y(FE_OFN141_n279), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS FE_RC_125_0 (
	.A0(FE_OFN257_n294),
	.A1(n491),
	.B0(n4901),
	.Y(n495), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS FE_RC_124_0 (
	.A(FE_OFN17_weight_in_1),
	.B(FE_OFN149_weight_in_0),
	.Y(FE_DBTN0_n34), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X2TS FE_RC_123_0 (
	.A0(FE_OCPN174_n294),
	.A1(n527),
	.B0(n366),
	.Y(n369), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X4TS FE_RC_122_0 (
	.A0(FE_OFN141_n279),
	.A1(n237),
	.B0(n254),
	.B1(FE_OFN129_n108),
	.Y(n256), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_121_0 (
	.A(n150),
	.B(n151),
	.Y(FE_RN_20_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS FE_RC_120_0 (
	.AN(n92),
	.B(FE_OFN112_FE_DBTN1_fire_in),
	.Y(FE_RN_70_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_119_0 (
	.A(n335),
	.B(FE_RN_70_0),
	.Y(FE_RN_71_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X2TS FE_RC_118_0 (
	.A(FE_OFN112_FE_DBTN1_fire_in),
	.B(n92),
	.Y(FE_RN_72_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS FE_RC_117_0 (
	.A0(n335),
	.A1(FE_RN_72_0),
	.B0(FE_RN_71_0),
	.Y(N57), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X2TS FE_RC_116_0 (
	.A0(FE_OCPN174_n294),
	.A1(n442),
	.B0(n441),
	.Y(n445), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS U514_dup (
	.A(n259),
	.B(n258),
	.Y(FE_RN_8), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS FE_RC_113_0 (
	.A(n378),
	.B(n373),
	.Y(FE_RN_63_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OR3X2TS FE_RC_112_0 (
	.A(n378),
	.B(n374),
	.C(n373),
	.Y(FE_RN_64_0), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS FE_RC_111_0 (
	.A(n378),
	.B(n374),
	.Y(FE_RN_65_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS FE_RC_110_0 (
	.A(FE_OCPN169_n294),
	.B(FE_RN_65_0),
	.Y(FE_RN_66_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS FE_RC_109_0 (
	.A(n378),
	.B(n373),
	.Y(FE_RN_67_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX2TS FE_RC_108_0 (
	.AN(FE_OCPN169_n294),
	.B(FE_RN_67_0),
	.Y(FE_RN_68_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X2TS FE_RC_105_0 (
	.A0(n534),
	.A1(n262),
	.B0(n261),
	.Y(n263), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_104_0 (
	.A(n121),
	.Y(FE_RN_59_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_103_0 (
	.A(FE_RN_62_0),
	.B(FE_RN_59_0),
	.Y(FE_RN_60_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS FE_RC_99_0 (
	.AN(n94),
	.B(FE_OFN115_FE_DBTN1_fire_in),
	.Y(FE_RN_56_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_98_0 (
	.A(n456),
	.B(FE_RN_56_0),
	.Y(FE_RN_57_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X2TS FE_RC_97_0 (
	.A(FE_OFN115_FE_DBTN1_fire_in),
	.B(n94),
	.Y(FE_RN_58_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS FE_RC_96_0 (
	.A0(n456),
	.A1(FE_RN_58_0),
	.B0(FE_RN_57_0),
	.Y(N56), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_94_0 (
	.A(tmp[4]),
	.Y(FE_RN_55_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI2BB1X2TS FE_RC_93_0 (
	.A0N(FE_RN_55_0),
	.A1N(FE_RN_20_0),
	.B0(FE_RN_17_0),
	.Y(n174), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS FE_RC_92_0 (
	.A(FE_OFN100_FE_DBTN1_fire_in),
	.B(n539),
	.Y(FE_RN_52_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS FE_RC_91_0 (
	.A(n5401),
	.B(FE_RN_52_0),
	.Y(FE_RN_53_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX1TS FE_RC_90_0 (
	.AN(FE_OFN100_FE_DBTN1_fire_in),
	.B(n539),
	.Y(FE_RN_54_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS FE_RC_89_0 (
	.A0(n5401),
	.A1(FE_RN_54_0),
	.B0(FE_RN_53_0),
	.Y(N49), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS FE_RC_84_0 (
	.A0(FE_OCPN175_n294),
	.A1(n384),
	.B0(n383),
	.Y(n389), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX6TS FE_RC_80_0 (
	.A(FE_DBTN2_weight_in_5),
	.Y(FE_OFN259_weight_in_5), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS FE_RC_79_0 (
	.A(n434),
	.B(n4301),
	.Y(FE_RN_41_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS FE_RC_78_0 (
	.A(n434),
	.B(n431),
	.Y(FE_RN_42_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX1TS FE_RC_77_0 (
	.AN(n4301),
	.B(FE_RN_42_0),
	.Y(FE_RN_43_0), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X1TS FE_RC_76_0 (
	.A(n434),
	.B(n431),
	.Y(FE_RN_44_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS FE_RC_75_0 (
	.A(FE_OCPN175_n294),
	.B(FE_RN_44_0),
	.Y(FE_RN_45_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS FE_RC_74_0 (
	.A(n434),
	.B(n4301),
	.Y(FE_RN_46_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX1TS FE_RC_73_0 (
	.AN(FE_OCPN175_n294),
	.B(FE_RN_46_0),
	.Y(FE_RN_47_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X4TS FE_RC_71_0 (
	.A0(n253),
	.A1(FE_OFN6_weight_in_5),
	.B0(FE_RN_1),
	.B1(n117),
	.Y(n142), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX8TS FE_OCPC263_data_in_4 (
	.A(FE_OFN28_data_in_4),
	.Y(FE_OFN260_data_in_4), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OCPC262_data_in_4 (
	.A(data_in[4]),
	.Y(FE_OFN28_data_in_4), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X4TS FE_RC_37_0_dup (
	.A(FE_RN_25_0),
	.B(FE_RN_26_0),
	.Y(FE_RN_7), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI2BB1X2TS U243_dup (
	.A0N(n213),
	.A1N(n212),
	.B0(n211),
	.Y(FE_RN_6), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U474_dup (
	.A(n188),
	.B(n187),
	.Y(FE_RN_5), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX6TS FE_OCPC261_n102 (
	.A(FE_RN_37_0),
	.Y(FE_OFN124_n102), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX8TS FE_OCPC260_n102 (
	.A(FE_RN_37_0),
	.Y(FE_OFN125_n102), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OCPC259_n102 (
	.A(FE_RN_37_0),
	.Y(FE_OFN123_n102), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX2TS FE_OCPC258_n102 (
	.A(FE_RN_9),
	.Y(FE_RN_2), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OCPC253_n294_dup (
	.A(FE_OFN262_n294),
	.Y(FE_RN_4), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS U211_dup (
	.A(FE_OFN124_n102),
	.B(n101),
	.Y(FE_RN_3), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX1TS FE_RC_70_0 (
	.A(n204),
	.Y(FE_RN_36_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS FE_RC_68_0 (
	.A(FE_RN_2),
	.B(FE_RN_36_0),
	.Y(FE_RN_38_0), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX1TS FE_RC_67_0 (
	.A(n253),
	.Y(FE_RN_39_0), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS FE_RC_66_0 (
	.A(n112),
	.Y(FE_RN_40_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI2BB1X4TS FE_RC_65_0 (
	.A0N(FE_RN_40_0),
	.A1N(FE_RN_39_0),
	.B0(FE_RN_38_0),
	.Y(n199), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_64_0 (
	.A(n209),
	.B(n210),
	.Y(FE_RN_35_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS FE_RC_63_0 (
	.A(n208),
	.B(FE_RN_35_0),
	.Y(n211), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS U402_dup (
	.A(FE_OCPN177_weight_in_3),
	.B(FE_OFN9_weight_in_4),
	.Y(FE_RN_1), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX6TS FE_OCPC255_n294 (
	.A(FE_OFN248_n294),
	.Y(FE_OCPN175_n294), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX6TS FE_OCPC254_n294 (
	.A(FE_OFN248_n294),
	.Y(FE_OCPN174_n294), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX6TS FE_OCPC253_n294 (
	.A(FE_OFN262_n294),
	.Y(FE_OFN163_n294), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX6TS FE_OCPC252_n294 (
	.A(FE_OFN262_n294),
	.Y(FE_OCPN169_n294), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX12TS FE_OCPC251_n294 (
	.A(FE_OFN262_n294),
	.Y(FE_OFN257_n294), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX4TS FE_OCPC250_n294 (
	.A(FE_OFN262_n294),
	.Y(FE_OFN92_n294), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX4TS FE_OCPC249_n294 (
	.A(n294),
	.Y(FE_OFN248_n294), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX8TS FE_OCPC248_n294 (
	.A(n294),
	.Y(FE_OFN262_n294), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS FE_RC_60_0 (
	.A0(n596),
	.A1(n597),
	.B0(n162),
	.Y(n591), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI2BB1X2TS FE_RC_55_0 (
	.A0N(n119),
	.A1N(n121),
	.B0(n105),
	.Y(n201), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OCPC247_n128 (
	.A(n128),
	.Y(FE_OCPN173_n128), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X4TS FE_RC_53_0 (
	.A0(n591),
	.A1(n588),
	.B0(n589),
	.Y(n584), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X2TS FE_RC_52_0 (
	.A0(FE_DBTN0_n34),
	.A1(n116),
	.B0(n111),
	.B1(FE_OFN149_weight_in_0),
	.Y(n122), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X4TS FE_RC_51_0 (
	.A0(n545),
	.A1(n544),
	.B0(n546),
	.Y(n290), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS FE_RC_43_0 (
	.A0(FE_OFN257_n294),
	.A1(n458),
	.B0(n4601),
	.Y(n301), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X2TS FE_RC_41_0 (
	.A0(n168),
	.A1(FE_OFN149_weight_in_0),
	.B0(FE_RN_11),
	.B1(n157),
	.Y(n170), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X4TS FE_RC_40_0 (
	.A0(FE_OFN249_n156),
	.A1(n143),
	.B0(FE_OFN139_n226),
	.B1(n164),
	.Y(n150), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OCPC244_n236 (
	.A(n236),
	.Y(FE_OCPN170_n236), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS FE_RC_39_0 (
	.A(n110),
	.B(FE_OFN131_n156),
	.Y(FE_RN_25_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS FE_RC_38_0 (
	.A(n129),
	.B(n226),
	.Y(FE_RN_26_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X4TS FE_RC_37_0 (
	.A(FE_RN_26_0),
	.B(FE_RN_25_0),
	.Y(n127), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X4TS FE_RC_36_0 (
	.A0(n74),
	.A1(n228),
	.B0(FE_OFN123_n102),
	.B1(n239),
	.Y(n236), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_35_0 (
	.A(FE_RN_20_0),
	.Y(FE_RN_16_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_34_0 (
	.A(FE_RN_16_0),
	.B(tmp[4]),
	.Y(FE_RN_17_0), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX2TS FE_RC_28_0 (
	.A(n150),
	.Y(FE_RN_22_0), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_27_0 (
	.A(n151),
	.Y(FE_RN_23_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI2BB1X4TS FE_RC_26_0 (
	.A0N(FE_RN_23_0),
	.A1N(FE_RN_22_0),
	.B0(tmp[4]),
	.Y(FE_RN_24_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS FE_RC_24_0 (
	.A(n170),
	.B(n171),
	.Y(FE_RN_10_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X2TS FE_RC_23_0 (
	.A(n170),
	.B(n171),
	.Y(FE_RN_11_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI2BB1X1TS FE_RC_22_0 (
	.A0N(tmp[2]),
	.A1N(FE_RN_11_0),
	.B0(FE_RN_10_0),
	.Y(n172), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX3TS FE_RC_21_0 (
	.A(FE_RN_14_0),
	.Y(FE_RN_12_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS FE_RC_20_0 (
	.A(FE_RN_12_0),
	.B(tmp[2]),
	.Y(FE_RN_13_0), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_19_0 (
	.A(n170),
	.B(n171),
	.Y(FE_RN_14_0), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X4TS FE_RC_17_0 (
	.A0(FE_RN_12_0),
	.A1(tmp[2]),
	.B0(FE_RN_13_0),
	.Y(n161), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X4TS FE_RC_15_0 (
	.A0(n569),
	.A1(n191),
	.B0(n190),
	.Y(n555), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_14_0 (
	.A(tmp[9]),
	.B(FE_OCPN170_n236),
	.Y(FE_RN_6_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_13_0 (
	.A(tmp[10]),
	.B(FE_OCPN170_n236),
	.Y(FE_RN_7_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS FE_RC_12_0 (
	.A(tmp[10]),
	.B(tmp[9]),
	.Y(FE_RN_8_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND3X4TS FE_RC_11_0 (
	.A(FE_RN_8_0),
	.B(FE_RN_7_0),
	.C(FE_RN_6_0),
	.Y(n250), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS FE_RC_10_0 (
	.A(n236),
	.B(tmp[9]),
	.Y(FE_RN_9_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_6_0 (
	.A(FE_OCPN173_n128),
	.B(FE_RN_7),
	.Y(FE_RN_3_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_5_0 (
	.A(tmp[6]),
	.B(FE_RN_7),
	.Y(FE_RN_4_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_4_0 (
	.A(FE_OCPN173_n128),
	.B(tmp[6]),
	.Y(FE_RN_5_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND3X2TS FE_RC_3_0 (
	.A(FE_RN_5_0),
	.B(FE_RN_4_0),
	.C(FE_RN_3_0),
	.Y(n124), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_RC_2_0 (
	.A(n196),
	.Y(FE_RN_0_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS FE_RC_1_0 (
	.A(n555),
	.B(n197),
	.Y(FE_RN_1_0), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X8TS FE_RC_0_0 (
	.A(FE_RN_1_0),
	.B(FE_RN_0_0),
	.Y(n293), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX3TS FE_OFC261_data_in_2 (
	.A(data_in[2]),
	.Y(FE_OFN261_data_in_2), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX6TS FE_OFC258_FE_DBTN0_n34 (
	.A(FE_RN_11),
	.Y(FE_OFN258_FE_DBTN0_n34), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX8TS FE_OFC255_weight_in_7 (
	.A(FE_OFN142_weight_in_7),
	.Y(FE_OFN255_weight_in_7), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX6TS FE_OFC242_n108 (
	.A(n108),
	.Y(FE_OFN168_n108), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX4TS FE_OFC250_data_in_0 (
	.A(FE_OFN245_data_in_0),
	.Y(FE_OFN250_data_in_0), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC249_n156 (
	.A(FE_OFN131_n156),
	.Y(FE_OFN249_n156), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX4TS FE_OFC247_weight_in_5 (
	.A(FE_OFN259_weight_in_5),
	.Y(FE_OFN247_weight_in_5), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC241_weight_in_7 (
	.A(FE_OFN240_weight_in_7),
	.Y(FE_OFN167_n), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC239_weight_in_7 (
	.A(FE_OFN240_weight_in_7),
	.Y(FE_OFN166_n), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX4TS FE_OFC238_weight_in_7 (
	.A(FE_OFN240_weight_in_7),
	.Y(FE_OFN165_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC246_data_in_5 (
	.A(data_in[5]),
	.Y(FE_OFN246_data_in_5), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX4TS FE_OFC245_data_in_0 (
	.A(data_in[0]),
	.Y(FE_OFN245_data_in_0), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX6TS FE_OFC244_weight_in_1 (
	.A(FE_OFN16_weight_in_1),
	.Y(FE_OFN244_weight_in_1), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX4TS FE_OFC243_weight_in_6 (
	.A(weight_in[6]),
	.Y(FE_OFN243_weight_in_6), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX2TS FE_OFC242_data_in_7 (
	.A(data_in[7]),
	.Y(FE_OFN242_data_in_7), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC240_weight_in_7 (
	.A(weight_in[7]),
	.Y(FE_OFN240_weight_in_7), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC239_fire_in (
	.A(fire_in),
	.Y(FE_OFN239_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC238_weight_in_4 (
	.A(weight_in[4]),
	.Y(FE_OFN238_weight_in_4), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC235_weight_in_5 (
	.A(weight_in[5]),
	.Y(FE_OFN235_weight_in_5), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX4TS FE_OFC234_FE_DBTN2_weight_in_5 (
	.A(FE_OFN259_weight_in_5),
	.Y(FE_OFN159_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX8TS FE_OFC233_FE_DBTN2_weight_in_5 (
	.A(FE_OFN259_weight_in_5),
	.Y(FE_OFN6_weight_in_5), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC231_n108 (
	.A(n108),
	.Y(FE_OFN161_n108), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX6TS FE_OFC230_n108 (
	.A(FE_OFN168_n108),
	.Y(FE_OFN129_n108), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX8TS FE_OFC229_weight_in_7 (
	.A(FE_OFN165_n),
	.Y(FE_OFN142_weight_in_7), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX2TS FE_OFC227_n412 (
	.A(n412),
	.Y(n415), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC225_n428 (
	.A(n428),
	.Y(n4401), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC224_n533 (
	.A(n533),
	.Y(n257), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX3TS FE_OFC223_n582 (
	.A(n582),
	.Y(n183), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX2TS FE_OFC222_n545 (
	.A(n545),
	.Y(n547), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC221_n156 (
	.A(n156),
	.Y(FE_OFN130_n156), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX8TS FE_OFC220_n156 (
	.A(n156),
	.Y(FE_OFN131_n156), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX6TS FE_OFC216_weight_in_5 (
	.A(FE_OFN235_weight_in_5),
	.Y(FE_DBTN2_weight_in_5), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC213_n424 (
	.A(n424),
	.Y(n437), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC202_data_in_3 (
	.A(data_in[3]),
	.Y(FE_OFN30_data_in_3), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC201_weight_in_2 (
	.A(weight_in[2]),
	.Y(FE_OFN15_weight_in_2), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC199_data_in_2 (
	.A(FE_OFN261_data_in_2),
	.Y(FE_OFN33_data_in_2), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX12TS FE_OFC197_weight_in_4 (
	.A(FE_OFN238_weight_in_4),
	.Y(FE_OFN9_weight_in_4), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC196_data_in_0 (
	.A(FE_OFN250_data_in_0),
	.Y(FE_OFN157_data_in_0), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX8TS FE_OFC195_data_in_0 (
	.A(FE_OFN250_data_in_0),
	.Y(FE_OFN39_data_in_0), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC191_data_in_6 (
	.A(FE_PDN278_data_in_6),
	.Y(FE_OFN25_data_in_6), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC190_data_in_5 (
	.A(FE_OFN246_data_in_5),
	.Y(FE_OFN27_data_in_5), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX6TS FE_OFC183_weight_in_1 (
	.A(FE_OFN244_weight_in_1),
	.Y(FE_OFN17_weight_in_1), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX8TS FE_OFC182_weight_in_1 (
	.A(FE_OFN244_weight_in_1),
	.Y(FE_OFN19_weight_in_1), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX4TS FE_OFC181_weight_in_1 (
	.A(weight_in[1]),
	.Y(FE_OFN16_weight_in_1), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC180_data_in_7 (
	.A(FE_OFN242_data_in_7),
	.Y(FE_OFN150_data_in_7), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC178_data_in_1 (
	.A(FE_OFN35_data_in_1),
	.Y(FE_OFN156_data_in_1), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC177_data_in_1 (
	.A(data_in[1]),
	.Y(FE_OFN35_data_in_1), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX4TS FE_OFC174_weight_in_0 (
	.A(n166),
	.Y(FE_OFN149_weight_in_0), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC172_weight_in_0 (
	.A(weight_in[0]),
	.Y(n166), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC158_rst_n (
	.A(rst_n),
	.Y(FE_OFN158_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX8TS FE_OFC139_n226 (
	.A(n226),
	.Y(FE_OFN139_n226), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX4TS FE_OFC138_n226 (
	.A(n226),
	.Y(FE_OFN138_n226), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC122_FE_DBTN1_fire_in (
	.A(FE_OFN120_FE_DBTN1_fire_in),
	.Y(FE_OFN122_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC121_FE_DBTN1_fire_in (
	.A(FE_OFN119_FE_DBTN1_fire_in),
	.Y(FE_OFN121_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC120_FE_DBTN1_fire_in (
	.A(FE_OFN119_FE_DBTN1_fire_in),
	.Y(FE_OFN120_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC119_FE_DBTN1_fire_in (
	.A(FE_OFN118_FE_DBTN1_fire_in),
	.Y(FE_OFN119_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC118_FE_DBTN1_fire_in (
	.A(FE_OFN116_FE_DBTN1_fire_in),
	.Y(FE_OFN118_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC117_FE_DBTN1_fire_in (
	.A(FE_OFN113_FE_DBTN1_fire_in),
	.Y(FE_OFN117_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC116_FE_DBTN1_fire_in (
	.A(FE_OFN113_FE_DBTN1_fire_in),
	.Y(FE_OFN116_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC115_FE_DBTN1_fire_in (
	.A(FE_OFN113_FE_DBTN1_fire_in),
	.Y(FE_OFN115_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC114_FE_DBTN1_fire_in (
	.A(FE_OFN110_FE_DBTN1_fire_in),
	.Y(FE_OFN114_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC113_FE_DBTN1_fire_in (
	.A(FE_OFN109_FE_DBTN1_fire_in),
	.Y(FE_OFN113_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC112_FE_DBTN1_fire_in (
	.A(FE_OFN108_FE_DBTN1_fire_in),
	.Y(FE_OFN112_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC111_FE_DBTN1_fire_in (
	.A(FE_OFN108_FE_DBTN1_fire_in),
	.Y(FE_OFN111_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC110_FE_DBTN1_fire_in (
	.A(FE_OFN107_FE_DBTN1_fire_in),
	.Y(FE_OFN110_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC109_FE_DBTN1_fire_in (
	.A(FE_OFN106_FE_DBTN1_fire_in),
	.Y(FE_OFN109_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC108_FE_DBTN1_fire_in (
	.A(FE_OFN105_FE_DBTN1_fire_in),
	.Y(FE_OFN108_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC107_FE_DBTN1_fire_in (
	.A(FE_OFN104_FE_DBTN1_fire_in),
	.Y(FE_OFN107_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC106_FE_DBTN1_fire_in (
	.A(FE_OFN102_FE_DBTN1_fire_in),
	.Y(FE_OFN106_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC105_FE_DBTN1_fire_in (
	.A(FE_OFN100_FE_DBTN1_fire_in),
	.Y(FE_OFN105_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC104_FE_DBTN1_fire_in (
	.A(FE_OFN99_FE_DBTN1_fire_in),
	.Y(FE_OFN104_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC103_FE_DBTN1_fire_in (
	.A(FE_OFN99_FE_DBTN1_fire_in),
	.Y(FE_OFN103_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC102_FE_DBTN1_fire_in (
	.A(FE_OFN98_FE_DBTN1_fire_in),
	.Y(FE_OFN102_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC101_FE_DBTN1_fire_in (
	.A(FE_OFN98_FE_DBTN1_fire_in),
	.Y(FE_OFN101_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC100_FE_DBTN1_fire_in (
	.A(FE_OFN97_FE_DBTN1_fire_in),
	.Y(FE_OFN100_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC99_FE_DBTN1_fire_in (
	.A(FE_DBTN1_fire_in),
	.Y(FE_OFN99_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC98_FE_DBTN1_fire_in (
	.A(FE_DBTN1_fire_in),
	.Y(FE_OFN98_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC97_FE_DBTN1_fire_in (
	.A(FE_DBTN1_fire_in),
	.Y(FE_OFN97_FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC89_fire_in (
	.A(FE_OFN88_fire_in),
	.Y(FE_OFN89_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC88_fire_in (
	.A(FE_OFN86_fire_in),
	.Y(FE_OFN88_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC87_fire_in (
	.A(FE_OFN86_fire_in),
	.Y(FE_OFN87_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC86_fire_in (
	.A(FE_OFN85_fire_in),
	.Y(FE_OFN86_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC85_fire_in (
	.A(FE_OFN84_fire_in),
	.Y(FE_OFN85_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC84_fire_in (
	.A(FE_OFN83_fire_in),
	.Y(FE_OFN84_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC83_fire_in (
	.A(FE_OFN80_fire_in),
	.Y(FE_OFN83_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC82_fire_in (
	.A(FE_OFN79_fire_in),
	.Y(FE_OFN82_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC81_fire_in (
	.A(FE_OFN79_fire_in),
	.Y(FE_OFN81_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC80_fire_in (
	.A(FE_OFN78_fire_in),
	.Y(FE_OFN80_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC79_fire_in (
	.A(FE_OFN77_fire_in),
	.Y(FE_OFN79_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC78_fire_in (
	.A(FE_OFN77_fire_in),
	.Y(FE_OFN78_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC77_fire_in (
	.A(FE_OFN239_fire_in),
	.Y(FE_OFN77_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX4TS FE_OFC75_rst_n (
	.A(FE_OFN73_rst_n),
	.Y(FE_OFN75_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC74_rst_n (
	.A(FE_OFN72_rst_n),
	.Y(FE_OFN74_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC73_rst_n (
	.A(FE_OFN72_rst_n),
	.Y(FE_OFN73_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC72_rst_n (
	.A(FE_OFN70_rst_n),
	.Y(FE_OFN72_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC71_rst_n (
	.A(FE_OFN69_rst_n),
	.Y(FE_OFN71_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC70_rst_n (
	.A(FE_OFN69_rst_n),
	.Y(FE_OFN70_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX4TS FE_OFC69_rst_n (
	.A(FE_OFN67_rst_n),
	.Y(FE_OFN69_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC68_rst_n (
	.A(FE_OFN65_rst_n),
	.Y(FE_OFN68_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX2TS FE_OFC67_rst_n (
	.A(FE_OFN64_rst_n),
	.Y(FE_OFN67_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC66_rst_n (
	.A(FE_OFN64_rst_n),
	.Y(FE_OFN66_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC65_rst_n (
	.A(FE_OFN63_rst_n),
	.Y(FE_OFN65_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC64_rst_n (
	.A(FE_OFN62_rst_n),
	.Y(FE_OFN64_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC63_rst_n (
	.A(FE_OFN61_rst_n),
	.Y(FE_OFN63_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC62_rst_n (
	.A(FE_OFN60_rst_n),
	.Y(FE_OFN62_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC61_rst_n (
	.A(FE_OFN59_rst_n),
	.Y(FE_OFN61_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC60_rst_n (
	.A(FE_OFN56_rst_n),
	.Y(FE_OFN60_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC59_rst_n (
	.A(FE_OFN55_rst_n),
	.Y(FE_OFN59_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC58_rst_n (
	.A(FE_OFN55_rst_n),
	.Y(FE_OFN58_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC57_rst_n (
	.A(FE_OFN54_rst_n),
	.Y(FE_OFN57_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX4TS FE_OFC56_rst_n (
	.A(FE_OFN54_rst_n),
	.Y(FE_OFN56_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC55_rst_n (
	.A(FE_OFN53_rst_n),
	.Y(FE_OFN55_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC54_rst_n (
	.A(FE_OFN52_rst_n),
	.Y(FE_OFN54_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC53_rst_n (
	.A(FE_OFN51_rst_n),
	.Y(FE_OFN53_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX6TS FE_OFC52_rst_n (
	.A(FE_OFN50_rst_n),
	.Y(FE_OFN52_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC51_rst_n (
	.A(FE_OFN50_rst_n),
	.Y(FE_OFN51_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC50_rst_n (
	.A(FE_OFN49_rst_n),
	.Y(FE_OFN50_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC49_rst_n (
	.A(FE_OFN48_rst_n),
	.Y(FE_OFN49_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC48_rst_n (
	.A(FE_OFN47_rst_n),
	.Y(FE_OFN48_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC47_rst_n (
	.A(FE_OFN45_rst_n),
	.Y(FE_OFN47_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC46_rst_n (
	.A(FE_OFN44_rst_n),
	.Y(FE_OFN46_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC45_rst_n (
	.A(FE_OFN44_rst_n),
	.Y(FE_OFN45_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS FE_OFC44_rst_n (
	.A(FE_OFN43_rst_n),
	.Y(FE_OFN44_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFX3TS FE_OFC43_rst_n (
	.A(FE_OFN158_rst_n),
	.Y(FE_OFN43_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKBUFX2TS FE_OFC41_data_out_0 (
	.A(FE_OFN41_data_out_0),
	.Y(data_out[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX3TS FE_DBTC1_fire_in (
	.A(FE_OFN78_fire_in),
	.Y(FE_DBTN1_fire_in), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS tmp_reg_13_ (
	.D(N50),
	.CK(clk),
	.RN(FE_OFN59_rst_n),
	.Q(tmp[13]),
	.QN(n89), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRX1TS tmp_reg_12_ (
	.D(N49),
	.CK(clk),
	.RN(FE_OFN59_rst_n),
	.Q(tmp[12]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRX1TS tmp_reg_11_ (
	.D(N48),
	.CK(clk),
	.RN(FE_OFN58_rst_n),
	.Q(tmp[11]),
	.QN(n85), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRX1TS tmp_reg_10_ (
	.D(N47),
	.CK(clk),
	.RN(FE_OFN53_rst_n),
	.Q(tmp[10]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRX4TS tmp_reg_8_ (
	.D(N45),
	.CK(clk),
	.RN(FE_OFN158_rst_n),
	.Q(tmp[8]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRX2TS tmp_reg_5_ (
	.D(N42),
	.CK(clk),
	.RN(FE_OFN43_rst_n),
	.Q(tmp[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRX2TS tmp_reg_2_ (
	.D(N39),
	.CK(clk),
	.RN(FE_OFN47_rst_n),
	.Q(tmp[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRX2TS tmp_reg_1_ (
	.D(N38),
	.CK(clk),
	.RN(FE_OFN49_rst_n),
	.Q(tmp[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRX2TS tmp_reg_0_ (
	.D(N37),
	.CK(clk),
	.RN(FE_OFN51_rst_n),
	.Q(tmp[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX1TS tmp_reg_3_ (
	.D(N40),
	.CK(clk),
	.RN(FE_OFN43_rst_n),
	.Q(tmp[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_7_ (
	.D(N44),
	.CK(clk),
	.RN(FE_OFN158_rst_n),
	.Q(tmp[7]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_9_ (
	.D(N46),
	.CK(clk),
	.RN(FE_OFN58_rst_n),
	.Q(tmp[9]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_14_ (
	.D(N51),
	.CK(clk),
	.RN(FE_OFN61_rst_n),
	.Q(tmp[14]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_16_ (
	.D(N53),
	.CK(clk),
	.RN(FE_OFN59_rst_n),
	.Q(tmp[16]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_24_ (
	.D(N61),
	.CK(clk),
	.RN(FE_OFN68_rst_n),
	.Q(tmp[24]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_20_ (
	.D(N57),
	.CK(clk),
	.RN(FE_OFN65_rst_n),
	.Q(tmp[20]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_27_ (
	.D(N64),
	.CK(clk),
	.RN(FE_OFN74_rst_n),
	.Q(tmp[27]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_25_ (
	.D(N62),
	.CK(clk),
	.RN(FE_OFN68_rst_n),
	.Q(tmp[25]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_23_ (
	.D(N60),
	.CK(clk),
	.RN(FE_OFN68_rst_n),
	.Q(tmp[23]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX4TS tmp_reg_21_ (
	.D(N58),
	.CK(clk),
	.RN(FE_OFN65_rst_n),
	.Q(tmp[21]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_19_ (
	.D(N56),
	.CK(clk),
	.RN(FE_OFN66_rst_n),
	.Q(tmp[19]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_17_ (
	.D(N54),
	.CK(clk),
	.RN(FE_OFN62_rst_n),
	.Q(tmp[17]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_26_ (
	.D(N63),
	.CK(clk),
	.RN(FE_OFN74_rst_n),
	.Q(tmp[26]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_31_ (
	.D(N68),
	.CK(clk),
	.RN(FE_OFN75_rst_n),
	.Q(tmp[31]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX4TS tmp_reg_15_ (
	.D(N52),
	.CK(clk),
	.RN(FE_OFN61_rst_n),
	.Q(tmp[15]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_29_ (
	.D(N66),
	.CK(clk),
	.RN(FE_OFN75_rst_n),
	.Q(tmp[29]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX4TS tmp_reg_18_ (
	.D(N55),
	.CK(clk),
	.RN(FE_OFN66_rst_n),
	.Q(tmp[18]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_30_ (
	.D(N67),
	.CK(clk),
	.RN(FE_OFN75_rst_n),
	.Q(tmp[30]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX2TS tmp_reg_28_ (
	.D(N65),
	.CK(clk),
	.RN(FE_OFN74_rst_n),
	.Q(tmp[28]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRHQX4TS tmp_reg_22_ (
	.D(N59),
	.CK(clk),
	.RN(FE_OFN68_rst_n),
	.Q(tmp[22]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS data_out_reg_6_ (
	.D(FE_PSN284_FE_OFN25_data_in_6),
	.CK(clk),
	.RN(FE_OFN61_rst_n),
	.Q(data_out[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_28_ (
	.D(n627),
	.CK(clk),
	.RN(FE_OFN71_rst_n),
	.Q(result[28]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_13_ (
	.D(n631),
	.CK(clk),
	.RN(FE_OFN60_rst_n),
	.Q(result[13]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRX2TS tmp_reg_4_ (
	.D(N41),
	.CK(clk),
	.RN(FE_OFN46_rst_n),
	.Q(tmp[4]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS data_out_reg_2_ (
	.D(FE_OFN33_data_in_2),
	.CK(clk),
	.RN(FE_OFN58_rst_n),
	.Q(data_out[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS data_out_reg_4_ (
	.D(FE_OFN260_data_in_4),
	.CK(clk),
	.RN(FE_OFN63_rst_n),
	.Q(data_out[4]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS weight_out_reg_6_ (
	.D(FE_OFN243_weight_in_6),
	.CK(clk),
	.RN(FE_OFN47_rst_n),
	.Q(weight_out[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS weight_out_reg_1_ (
	.D(FE_OFN19_weight_in_1),
	.CK(clk),
	.RN(FE_OFN45_rst_n),
	.Q(weight_out[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS fire_out_reg (
	.D(FE_OFN82_fire_in),
	.CK(clk),
	.RN(FE_OFN48_rst_n),
	.Q(fire_out), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS weight_out_reg_2_ (
	.D(FE_OFN15_weight_in_2),
	.CK(clk),
	.RN(FE_OFN46_rst_n),
	.Q(weight_out[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS weight_out_reg_0_ (
	.D(n166),
	.CK(clk),
	.RN(FE_OFN46_rst_n),
	.Q(weight_out[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS data_out_reg_7_ (
	.D(FE_OFN150_data_in_7),
	.CK(clk),
	.RN(FE_OFN63_rst_n),
	.Q(data_out[7]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS data_out_reg_5_ (
	.D(FE_OFN27_data_in_5),
	.CK(clk),
	.RN(FE_OFN63_rst_n),
	.Q(data_out[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS data_out_reg_3_ (
	.D(FE_OCPN178_FE_OFN30_data_in_3),
	.CK(clk),
	.RN(FE_OFN58_rst_n),
	.Q(data_out[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS data_out_reg_1_ (
	.D(FE_OFN156_data_in_1),
	.CK(clk),
	.RN(FE_OFN55_rst_n),
	.Q(data_out[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS data_out_reg_0_ (
	.D(FE_OFN157_data_in_0),
	.CK(clk),
	.RN(FE_OFN53_rst_n),
	.Q(FE_OFN41_data_out_0), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS weight_out_reg_5_ (
	.D(FE_OFN247_weight_in_5),
	.CK(clk),
	.RN(FE_OFN45_rst_n),
	.Q(weight_out[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS weight_out_reg_3_ (
	.D(FE_OFN11_weight_in_3),
	.CK(clk),
	.RN(FE_OFN43_rst_n),
	.Q(weight_out[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS weight_out_reg_4_ (
	.D(FE_OFN9_weight_in_4),
	.CK(clk),
	.RN(FE_OFN45_rst_n),
	.Q(weight_out[4]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS weight_out_reg_7_ (
	.D(FE_OFN166_n),
	.CK(clk),
	.RN(FE_OFN47_rst_n),
	.Q(weight_out[7]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_31_ (
	.D(n644),
	.CK(clk),
	.RN(FE_OFN71_rst_n),
	.Q(result[31]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_30_ (
	.D(n629),
	.CK(clk),
	.RN(FE_OFN75_rst_n),
	.Q(result[30]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_29_ (
	.D(n628),
	.CK(clk),
	.RN(FE_OFN71_rst_n),
	.Q(result[29]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_27_ (
	.D(n626),
	.CK(clk),
	.RN(FE_OFN69_rst_n),
	.Q(result[27]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_26_ (
	.D(n625),
	.CK(clk),
	.RN(FE_OFN73_rst_n),
	.Q(result[26]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_25_ (
	.D(n624),
	.CK(clk),
	.RN(FE_OFN70_rst_n),
	.Q(result[25]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_24_ (
	.D(n623),
	.CK(clk),
	.RN(FE_OFN66_rst_n),
	.Q(result[24]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_23_ (
	.D(n622),
	.CK(clk),
	.RN(FE_OFN70_rst_n),
	.Q(result[23]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_22_ (
	.D(n621),
	.CK(clk),
	.RN(FE_OFN71_rst_n),
	.Q(result[22]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_21_ (
	.D(n6201),
	.CK(clk),
	.RN(FE_OFN67_rst_n),
	.Q(result[21]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_20_ (
	.D(n619),
	.CK(clk),
	.RN(FE_OFN69_rst_n),
	.Q(result[20]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_19_ (
	.D(n618),
	.CK(clk),
	.RN(FE_OFN67_rst_n),
	.Q(result[19]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_18_ (
	.D(n617),
	.CK(clk),
	.RN(FE_OFN67_rst_n),
	.Q(result[18]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_17_ (
	.D(n616),
	.CK(clk),
	.RN(FE_OFN62_rst_n),
	.Q(result[17]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_16_ (
	.D(n615),
	.CK(clk),
	.RN(FE_OFN62_rst_n),
	.Q(result[16]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_15_ (
	.D(n614),
	.CK(clk),
	.RN(FE_OFN60_rst_n),
	.Q(result[15]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_14_ (
	.D(n637),
	.CK(clk),
	.RN(FE_OFN60_rst_n),
	.Q(result[14]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_12_ (
	.D(n639),
	.CK(clk),
	.RN(FE_OFN56_rst_n),
	.Q(result[12]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_11_ (
	.D(n613),
	.CK(clk),
	.RN(FE_OFN56_rst_n),
	.Q(result[11]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_10_ (
	.D(n636),
	.CK(clk),
	.RN(FE_OFN57_rst_n),
	.Q(result[10]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_9_ (
	.D(n6301),
	.CK(clk),
	.RN(FE_OFN56_rst_n),
	.Q(result[9]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_8_ (
	.D(n634),
	.CK(clk),
	.RN(FE_OFN55_rst_n),
	.Q(result[8]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_7_ (
	.D(n632),
	.CK(clk),
	.RN(FE_OFN53_rst_n),
	.Q(result[7]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_6_ (
	.D(n6401),
	.CK(clk),
	.RN(FE_OFN51_rst_n),
	.Q(result[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_5_ (
	.D(n643),
	.CK(clk),
	.RN(FE_OFN51_rst_n),
	.Q(result[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_4_ (
	.D(n638),
	.CK(clk),
	.RN(FE_OFN52_rst_n),
	.Q(result[4]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_3_ (
	.D(n642),
	.CK(clk),
	.RN(FE_OFN57_rst_n),
	.Q(result[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_2_ (
	.D(n635),
	.CK(clk),
	.RN(FE_OFN49_rst_n),
	.Q(result[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_1_ (
	.D(n641),
	.CK(clk),
	.RN(FE_OFN48_rst_n),
	.Q(result[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRXLTS result_reg_0_ (
	.D(n633),
	.CK(clk),
	.RN(FE_OFN52_rst_n),
	.Q(result[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFRX2TS tmp_reg_6_ (
	.D(N43),
	.CK(clk),
	.RN(FE_OFN158_rst_n),
	.Q(tmp[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX4TS U69 (
	.AN(n5301),
	.B(FE_OFN105_FE_DBTN1_fire_in),
	.Y(N51), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS U73 (
	.A(n4201),
	.B(n96),
	.Y(n422), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U77 (
	.A(n365),
	.B(n318),
	.Y(n424), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X4TS U78 (
	.A(n192),
	.B(n193),
	.Y(n563), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U79 (
	.A(n296),
	.B(n295),
	.Y(n365), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X6TS U80 (
	.A(n259),
	.B(n258),
	.Y(n537), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDHX2TS U81 (
	.A(tmp[3]),
	.B(n169),
	.S(n177),
	.CO(n175), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX2TS U82 (
	.A(tmp[12]),
	.B(tmp[11]),
	.CI(n269),
	.S(n266),
	.CO(n275), 
	.VSS(VSS), 
	.VDD(VDD));
   AO21X2TS U83 (
	.A0(FE_OFN141_n279),
	.A1(FE_OFN129_n108),
	.B0(n277),
	.Y(n280), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X2TS U85 (
	.A0(n104),
	.A1(FE_OFN161_n108),
	.B0(n103),
	.Y(n119), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U92 (
	.A(n406),
	.Y(n344), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U93 (
	.A(n482),
	.Y(n326), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X4TS U95 (
	.A0(FE_RN_3),
	.A1(n130),
	.B0(FE_OFN125_n102),
	.B1(n115),
	.Y(n135), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21XLTS U96 (
	.A0(n392),
	.A1(n347),
	.B0(n346),
	.Y(n348), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U97 (
	.A(n447),
	.Y(n4501), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2XLTS U98 (
	.A(n354),
	.B(tmp[28]),
	.Y(n375), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U99 (
	.A(tmp[23]),
	.Y(n324), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U100 (
	.A(tmp[24]),
	.Y(n331), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U101 (
	.A(n385),
	.Y(n387), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U102 (
	.A(n526),
	.Y(n366), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X1TS U103 (
	.A(n309),
	.B(tmp[18]),
	.Y(n455), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U105 (
	.A(n462),
	.Y(n304), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U106 (
	.A(n6001),
	.Y(n602), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U107 (
	.A(FE_PSN286_n544),
	.Y(n5501), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U112 (
	.A(n35),
	.B(FE_OFN97_FE_DBTN1_fire_in),
	.Y(N47), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U113 (
	.A(n4001),
	.Y(n396), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS U114 (
	.A0(n403),
	.A1(n402),
	.B0(n401),
	.Y(n404), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U115 (
	.A(n403),
	.Y(n395), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U116 (
	.A(n411),
	.B(n414),
	.Y(n417), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U118 (
	.A(n4101),
	.Y(n411), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U119 (
	.A(n371),
	.Y(n374), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U120 (
	.A(n479),
	.Y(n4801), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U121 (
	.A(n371),
	.B(n375),
	.Y(n471), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U122 (
	.A(n372),
	.Y(n373), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS U123 (
	.A0(n479),
	.A1(n429),
	.B0(n482),
	.Y(n4301), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U124 (
	.A(n478),
	.Y(n481), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U125 (
	.A(n437),
	.B(n330),
	.Y(n4101), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U126 (
	.A(n563),
	.Y(n564), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS U127 (
	.A0(n463),
	.A1(n462),
	.B0(n461),
	.Y(n464), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS U128 (
	.A0(n489),
	.A1(n451),
	.B0(n492),
	.Y(n452), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U130 (
	.A(n488),
	.Y(n491), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U131 (
	.A(n489),
	.Y(n4901), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U132 (
	.A(n458),
	.Y(n459), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U133 (
	.A(n4601),
	.Y(n463), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U134 (
	.A(n532),
	.Y(n260), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U136 (
	.A(n212),
	.Y(n210), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U137 (
	.A(n588),
	.Y(n5901), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U138 (
	.A(n367),
	.Y(n316), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U139 (
	.A(n595),
	.Y(n162), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U140 (
	.A(n382),
	.B(n385),
	.Y(n353), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS U141 (
	.A0(n381),
	.A1(n385),
	.B0(n386),
	.Y(n352), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U142 (
	.A(n350),
	.Y(n329), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U143 (
	.A(n338),
	.Y(n330), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS U144 (
	.A0(n448),
	.A1(n313),
	.B0(n312),
	.Y(n314), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U145 (
	.A(n447),
	.B(n313),
	.Y(n315), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U146 (
	.A(n425),
	.Y(n426), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U147 (
	.A(n391),
	.B(n347),
	.Y(n349), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U148 (
	.A(n423),
	.B(n328),
	.Y(n338), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U149 (
	.A(n423),
	.Y(n427), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS U150 (
	.A0(n425),
	.A1(n328),
	.B0(n327),
	.Y(n350), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U151 (
	.A(n392),
	.Y(n393), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U152 (
	.A(n448),
	.Y(n449), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X2TS U154 (
	.A(n377),
	.B(n376),
	.Y(n378), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X2TS U155 (
	.A(n493),
	.B(n492),
	.Y(n494), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X2TS U156 (
	.A(n433),
	.B(n432),
	.Y(n434), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X2TS U157 (
	.A(n407),
	.B(n406),
	.Y(n91), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U158 (
	.A(n375),
	.Y(n377), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U159 (
	.A(n402),
	.Y(n397), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U160 (
	.A(n472),
	.Y(n356), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U161 (
	.A(n401),
	.Y(n345), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U162 (
	.A(n413),
	.Y(n341), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U163 (
	.A(n418),
	.Y(n340), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U164 (
	.A(n414),
	.Y(n337), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U165 (
	.A(n461),
	.Y(n307), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U166 (
	.A(n443),
	.Y(n321), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U167 (
	.A(n466),
	.Y(n306), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U168 (
	.A(n454),
	.Y(n310), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U169 (
	.A(n451),
	.Y(n493), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U170 (
	.A(n492),
	.Y(n311), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U171 (
	.A(n432),
	.Y(n325), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U172 (
	.A(n439),
	.Y(n334), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U173 (
	.A(n438),
	.Y(n322), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U174 (
	.A(n429),
	.Y(n483), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2XLTS U179 (
	.A(n360),
	.B(tmp[30]),
	.Y(n361), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U180 (
	.A(n351),
	.B(tmp[27]),
	.Y(n385), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U181 (
	.A(n308),
	.B(tmp[17]),
	.Y(n451), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X2TS U182 (
	.A(n355),
	.B(tmp[29]),
	.Y(n473), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U183 (
	.A(n342),
	.B(tmp[25]),
	.Y(n402), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U184 (
	.A(n331),
	.B(tmp[23]),
	.Y(n414), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X2TS U185 (
	.A(n343),
	.B(tmp[26]),
	.Y(n407), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X2TS U186 (
	.A(n324),
	.B(tmp[22]),
	.Y(n433), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X2TS U187 (
	.A(n339),
	.B(tmp[24]),
	.Y(n419), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U188 (
	.A(n319),
	.B(tmp[19]),
	.Y(n439), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U189 (
	.A(n323),
	.B(tmp[21]),
	.Y(n429), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X2TS U190 (
	.A(n320),
	.B(tmp[20]),
	.Y(n444), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X2TS U191 (
	.A(n305),
	.B(tmp[16]),
	.Y(n467), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U192 (
	.A(tmp[21]),
	.Y(n320), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U193 (
	.A(tmp[20]),
	.Y(n319), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U194 (
	.A(tmp[22]),
	.Y(n323), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U195 (
	.A(tmp[19]),
	.Y(n309), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U196 (
	.A(tmp[16]),
	.Y(n299), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U197 (
	.A(tmp[18]),
	.Y(n308), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U198 (
	.A(tmp[17]),
	.Y(n305), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U199 (
	.A(tmp[31]),
	.Y(n360), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U200 (
	.A(tmp[28]),
	.Y(n351), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U201 (
	.A(tmp[29]),
	.Y(n354), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U202 (
	.A(tmp[27]),
	.Y(n343), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U203 (
	.A(tmp[30]),
	.Y(n355), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U204 (
	.A(tmp[26]),
	.Y(n342), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U205 (
	.A(tmp[25]),
	.Y(n339), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X2TS U208 (
	.A0(FE_OFN138_n226),
	.A1(n106),
	.B0(FE_OFN130_n156),
	.B1(n206),
	.Y(n205), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X6TS U209 (
	.A(n537),
	.B(n284),
	.Y(n287), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X4TS U210 (
	.A0(n74),
	.A1(n239),
	.B0(n251),
	.B1(FE_OFN123_n102),
	.Y(n255), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS U211 (
	.A(n101),
	.B(FE_OFN125_n102),
	.Y(n74), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS U212 (
	.A(n98),
	.B(n156),
	.Y(n226), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U213 (
	.A(n281),
	.Y(n531), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS U214 (
	.A(n281),
	.B(n289),
	.Y(n292), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS U215 (
	.A0(n526),
	.A1(n303),
	.B0(n367),
	.Y(n4601), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS U216 (
	.A(n296),
	.B(n295),
	.Y(n526), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X4TS U217 (
	.A0(n318),
	.A1(n526),
	.B0(n317),
	.Y(n428), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U218 (
	.A(tmp[15]),
	.Y(n297), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U219 (
	.A(n298),
	.B(n297),
	.Y(n303), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U220 (
	.A(FE_OFN242_data_in_7),
	.B(FE_OFN11_weight_in_3),
	.Y(n224), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U222 (
	.A(FE_OFN11_weight_in_3),
	.B(FE_OFN35_data_in_1),
	.Y(n164), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BXLTS U223 (
	.AN(FE_OFN245_data_in_0),
	.B(FE_OFN11_weight_in_3),
	.Y(n148), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X2TS U224 (
	.A0(n412),
	.A1(n394),
	.B0(n393),
	.Y(n403), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BXLTS U225 (
	.AN(FE_OFN157_data_in_0),
	.B(FE_OFN19_weight_in_1),
	.Y(n153), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X2TS U227 (
	.A(n471),
	.B(n473),
	.Y(n359), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U228 (
	.A(n459),
	.B(n462),
	.Y(n465), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U229 (
	.A(n488),
	.B(n451),
	.Y(n453), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21XLTS U230 (
	.A0(n4401),
	.A1(n439),
	.B0(n438),
	.Y(n441), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2XLTS U231 (
	.A(n437),
	.B(n439),
	.Y(n442), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U232 (
	.A(n4001),
	.B(n402),
	.Y(n405), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X2TS U233 (
	.A0(n4401),
	.A1(n330),
	.B0(n329),
	.Y(n412), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U235 (
	.A(n365),
	.B(n303),
	.Y(n458), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS U236 (
	.A(n571),
	.B(n5701),
	.Y(n572), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U238 (
	.A(n556),
	.Y(n558), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX4TS U239 (
	.A(n293),
	.Y(n553), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX1TS U241 (
	.AN(FE_OFN39_data_in_0),
	.B(FE_OFN167_n),
	.Y(n104), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U242 (
	.A(tmp[9]),
	.Y(n218), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U245 (
	.A(n213),
	.Y(n209), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX2TS U246 (
	.AN(FE_OFN250_data_in_0),
	.B(FE_OFN247_weight_in_5),
	.Y(n117), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX2TS U247 (
	.AN(FE_OFN245_data_in_0),
	.B(FE_RN_1),
	.Y(n151), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X6TS U249 (
	.A(n244),
	.B(n243),
	.Y(n533), 
	.VSS(VSS), 
	.VDD(VDD));
   AO21X1TS U250 (
	.A0(n75),
	.A1(FE_OFN125_n102),
	.B0(n251),
	.Y(n267), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U251 (
	.A(n182),
	.Y(n180), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21XLTS U252 (
	.A0(n4401),
	.A1(n382),
	.B0(n381),
	.Y(n383), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2XLTS U253 (
	.A(n437),
	.B(n382),
	.Y(n384), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2XLTS U254 (
	.A(n478),
	.B(n429),
	.Y(n431), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS U255 (
	.A(n571),
	.B(n5701),
	.Y(n578), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U257 (
	.A0(FE_OFN80_fire_in),
	.A1(result[13]),
	.B0(tmp[13]),
	.B1(FE_OFN102_FE_DBTN1_fire_in),
	.Y(n631), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U258 (
	.A0(FE_OFN89_fire_in),
	.A1(result[28]),
	.B0(tmp[28]),
	.B1(FE_OFN118_FE_DBTN1_fire_in),
	.Y(n627), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U259 (
	.A(n487),
	.B(FE_OFN111_FE_DBTN1_fire_in),
	.Y(N59), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS U260 (
	.A(n485),
	.B(n484),
	.Y(n487), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS U261 (
	.A(n368),
	.B(n367),
	.Y(n95), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS U262 (
	.A(n362),
	.B(n361),
	.Y(n93), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS U263 (
	.A(n397),
	.B(n401),
	.Y(n90), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS U264 (
	.A(n467),
	.B(n466),
	.Y(n87), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS U265 (
	.A(n455),
	.B(n454),
	.Y(n94), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS U266 (
	.A(n444),
	.B(n443),
	.Y(n88), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS U267 (
	.A(n419),
	.B(n418),
	.Y(n96), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS U268 (
	.A(n334),
	.B(n438),
	.Y(n92), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS U269 (
	.A(n337),
	.B(n413),
	.Y(n86), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2XLTS U271 (
	.A(n567),
	.B(n566),
	.Y(n568), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X1TS U272 (
	.A(n576),
	.B(n575),
	.Y(n577), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2XLTS U273 (
	.A(n592),
	.B(n591),
	.Y(n594), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U274 (
	.A0(FE_OFN82_fire_in),
	.A1(result[0]),
	.B0(tmp[0]),
	.B1(FE_OFN104_FE_DBTN1_fire_in),
	.Y(n633), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U275 (
	.A0(FE_OFN82_fire_in),
	.A1(result[1]),
	.B0(tmp[1]),
	.B1(FE_OFN104_FE_DBTN1_fire_in),
	.Y(n641), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U276 (
	.A0(FE_OFN82_fire_in),
	.A1(result[2]),
	.B0(tmp[2]),
	.B1(FE_OFN104_FE_DBTN1_fire_in),
	.Y(n635), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U277 (
	.A0(FE_OFN81_fire_in),
	.A1(result[3]),
	.B0(tmp[3]),
	.B1(FE_OFN101_FE_DBTN1_fire_in),
	.Y(n642), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U278 (
	.A0(FE_OFN77_fire_in),
	.A1(result[4]),
	.B0(tmp[4]),
	.B1(FE_OFN99_FE_DBTN1_fire_in),
	.Y(n638), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U279 (
	.A0(FE_OFN239_fire_in),
	.A1(result[5]),
	.B0(tmp[5]),
	.B1(FE_OFN103_FE_DBTN1_fire_in),
	.Y(n643), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U280 (
	.A0(FE_OFN239_fire_in),
	.A1(result[6]),
	.B0(tmp[6]),
	.B1(FE_OFN103_FE_DBTN1_fire_in),
	.Y(n6401), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U281 (
	.A0(FE_OFN77_fire_in),
	.A1(result[7]),
	.B0(tmp[7]),
	.B1(FE_OFN99_FE_DBTN1_fire_in),
	.Y(n632), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U282 (
	.A0(FE_OFN78_fire_in),
	.A1(result[8]),
	.B0(tmp[8]),
	.B1(FE_DBTN1_fire_in),
	.Y(n634), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U283 (
	.A0(FE_OFN78_fire_in),
	.A1(result[9]),
	.B0(tmp[9]),
	.B1(FE_OFN98_FE_DBTN1_fire_in),
	.Y(n6301), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U284 (
	.A0(FE_OFN81_fire_in),
	.A1(result[10]),
	.B0(tmp[10]),
	.B1(FE_OFN101_FE_DBTN1_fire_in),
	.Y(n636), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U285 (
	.A0(FE_OFN81_fire_in),
	.A1(result[11]),
	.B0(tmp[11]),
	.B1(FE_OFN101_FE_DBTN1_fire_in),
	.Y(n613), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U286 (
	.A0(FE_OFN80_fire_in),
	.A1(result[12]),
	.B0(tmp[12]),
	.B1(FE_OFN102_FE_DBTN1_fire_in),
	.Y(n639), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U287 (
	.A0(FE_OFN80_fire_in),
	.A1(result[14]),
	.B0(tmp[14]),
	.B1(FE_OFN102_FE_DBTN1_fire_in),
	.Y(n637), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U288 (
	.A0(FE_OFN83_fire_in),
	.A1(result[15]),
	.B0(tmp[15]),
	.B1(FE_OFN106_FE_DBTN1_fire_in),
	.Y(n614), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U289 (
	.A0(FE_OFN83_fire_in),
	.A1(result[16]),
	.B0(tmp[16]),
	.B1(FE_OFN106_FE_DBTN1_fire_in),
	.Y(n615), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U290 (
	.A0(FE_OFN83_fire_in),
	.A1(result[17]),
	.B0(tmp[17]),
	.B1(FE_OFN109_FE_DBTN1_fire_in),
	.Y(n616), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U291 (
	.A0(FE_OFN84_fire_in),
	.A1(result[18]),
	.B0(tmp[18]),
	.B1(FE_OFN109_FE_DBTN1_fire_in),
	.Y(n617), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U292 (
	.A0(FE_OFN84_fire_in),
	.A1(result[19]),
	.B0(tmp[19]),
	.B1(FE_OFN113_FE_DBTN1_fire_in),
	.Y(n618), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U293 (
	.A0(FE_OFN84_fire_in),
	.A1(result[20]),
	.B0(tmp[20]),
	.B1(FE_OFN117_FE_DBTN1_fire_in),
	.Y(n619), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U294 (
	.A0(FE_OFN85_fire_in),
	.A1(result[21]),
	.B0(tmp[21]),
	.B1(FE_OFN117_FE_DBTN1_fire_in),
	.Y(n6201), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U295 (
	.A0(FE_OFN88_fire_in),
	.A1(result[22]),
	.B0(tmp[22]),
	.B1(FE_OFN117_FE_DBTN1_fire_in),
	.Y(n621), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U296 (
	.A0(FE_OFN85_fire_in),
	.A1(result[23]),
	.B0(tmp[23]),
	.B1(FE_OFN116_FE_DBTN1_fire_in),
	.Y(n622), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U297 (
	.A0(FE_OFN85_fire_in),
	.A1(result[24]),
	.B0(tmp[24]),
	.B1(FE_OFN116_FE_DBTN1_fire_in),
	.Y(n623), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U298 (
	.A0(FE_OFN87_fire_in),
	.A1(result[25]),
	.B0(tmp[25]),
	.B1(FE_OFN118_FE_DBTN1_fire_in),
	.Y(n624), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U299 (
	.A0(FE_OFN87_fire_in),
	.A1(result[26]),
	.B0(tmp[26]),
	.B1(FE_OFN120_FE_DBTN1_fire_in),
	.Y(n625), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U300 (
	.A0(FE_OFN87_fire_in),
	.A1(result[27]),
	.B0(tmp[27]),
	.B1(FE_OFN116_FE_DBTN1_fire_in),
	.Y(n626), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U301 (
	.A0(FE_OFN89_fire_in),
	.A1(result[29]),
	.B0(tmp[29]),
	.B1(FE_OFN118_FE_DBTN1_fire_in),
	.Y(n628), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U302 (
	.A0(FE_OFN89_fire_in),
	.A1(result[30]),
	.B0(tmp[30]),
	.B1(FE_OFN122_FE_DBTN1_fire_in),
	.Y(n629), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22XLTS U303 (
	.A0(FE_OFN89_fire_in),
	.A1(result[31]),
	.B0(tmp[31]),
	.B1(FE_OFN122_FE_DBTN1_fire_in),
	.Y(n644), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKAND2X2TS U305 (
	.A(n607),
	.B(n606),
	.Y(n609), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2XLTS U306 (
	.A(n603),
	.B(n606),
	.Y(n604), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U307 (
	.A(n558),
	.B(n557),
	.Y(n559), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS U309 (
	.A(n549),
	.B(n548),
	.Y(n35), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U310 (
	.A(n547),
	.B(n546),
	.Y(n548), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X4TS U311 (
	.A(n543),
	.B(n545),
	.Y(n281), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X8TS U317 (
	.A(n232),
	.B(n231),
	.Y(n545), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U331 (
	.A(FE_OFN11_weight_in_3),
	.B(FE_OFN261_data_in_2),
	.Y(n143), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X4TS U347 (
	.A0(FE_OFN138_n226),
	.A1(n206),
	.B0(n224),
	.B1(FE_OFN130_n156),
	.Y(n219), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS U363 (
	.A(FE_RN_9),
	.B(n101),
	.Y(n253), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X2TS U373 (
	.A0(n553),
	.A1(n264),
	.B0(n263),
	.Y(n273), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX4TS U374 (
	.A(n235),
	.B(n234),
	.CI(n233),
	.S(n232),
	.CO(n244), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX2TS U375 (
	.A(n242),
	.B(n241),
	.CI(n240),
	.S(n233),
	.CO(n248), 
	.VSS(VSS), 
	.VDD(VDD));
   OA21X4TS U376 (
	.A0(n293),
	.A1(n531),
	.B0(n534),
	.Y(n246), 
	.VSS(VSS), 
	.VDD(VDD));
   CMPR22X2TS U377 (
	.A(tmp[7]),
	.B(n107),
	.S(n125),
	.CO(n202), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX2TS U379 (
	.A(n126),
	.B(n125),
	.CI(n124),
	.S(n136),
	.CO(n212), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS U380 (
	.A0(n121),
	.A1(n119),
	.B0(n122),
	.Y(n105), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X4TS U382 (
	.A(n152),
	.B(n5701),
	.Y(n97), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U383 (
	.A(n282),
	.Y(n283), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS U384 (
	.A0(n285),
	.A1(n284),
	.B0(n283),
	.Y(n286), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDHX1TS U385 (
	.A(tmp[1]),
	.B(n158),
	.S(n155),
	.CO(n160), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X4TS U386 (
	.A(n230),
	.B(FE_RN_6),
	.Y(n543), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U387 (
	.A(n365),
	.Y(n527), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U393 (
	.A(FE_OFN11_weight_in_3),
	.B(FE_OFN246_data_in_5),
	.Y(n106), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS U395 (
	.A(FE_PSN281_n205),
	.B(tmp[8]),
	.Y(n203), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X2TS U396 (
	.A(FE_OFN240_weight_in_7),
	.B(FE_OFN243_weight_in_6),
	.Y(n99), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS U398 (
	.A(n99),
	.B(n108),
	.Y(n279), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1TS U399 (
	.A(FE_OFN39_data_in_0),
	.B(FE_OFN165_n),
	.Y(n100), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U400 (
	.A(FE_OFN156_data_in_1),
	.B(FE_OFN166_n),
	.Y(n113), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X2TS U401 (
	.A0(n100),
	.A1(n279),
	.B0(n113),
	.B1(n108),
	.Y(n107), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS U403 (
	.A(FE_OFN247_weight_in_5),
	.B(FE_OFN33_data_in_2),
	.Y(n115), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X1TS U404 (
	.A(FE_OCPN178_FE_OFN30_data_in_3),
	.B(FE_OFN6_weight_in_5),
	.Y(n112), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X2TS U405 (
	.A0(n75),
	.A1(n115),
	.B0(n112),
	.B1(FE_OFN124_n102),
	.Y(n121), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX2TS U406 (
	.AN(n279),
	.B(FE_OFN167_n),
	.Y(n103), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1TS U407 (
	.A(FE_OFN244_weight_in_1),
	.B(FE_RN_10),
	.Y(n116), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1TS U408 (
	.A(FE_OFN244_weight_in_1),
	.B(FE_OFN242_data_in_7),
	.Y(n111), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U410 (
	.A(FE_OCPN177_weight_in_3),
	.B(FE_OFN28_data_in_4),
	.Y(n110), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X2TS U411 (
	.A0(FE_OFN138_n226),
	.A1(FE_PSN283_n110),
	.B0(n106),
	.B1(FE_OFN130_n156),
	.Y(n126), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX4TS U412 (
	.AN(FE_OFN39_data_in_0),
	.B(FE_OFN161_n108),
	.Y(n128), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U413 (
	.A(FE_OCPN177_weight_in_3),
	.B(FE_OFN30_data_in_3),
	.Y(n129), 
	.VSS(VSS), 
	.VDD(VDD));
   AO21X2TS U415 (
	.A0(FE_DBTN0_n34),
	.A1(FE_OFN149_weight_in_0),
	.B0(n111),
	.Y(n200), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS U416 (
	.A(FE_OFN159_n),
	.B(FE_OFN260_data_in_4),
	.Y(n204), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X1TS U418 (
	.A0(FE_OFN256_n279),
	.A1(n113),
	.B0(FE_OFN168_n108),
	.B1(n207),
	.Y(n198), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U421 (
	.A(FE_OFN17_weight_in_1),
	.B(FE_OFN246_data_in_5),
	.Y(n132), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X2TS U422 (
	.A0(FE_DBTN0_n34),
	.A1(n132),
	.B0(n116),
	.B1(FE_OFN149_weight_in_0),
	.Y(n134), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X4TS U426 (
	.A(n195),
	.B(n194),
	.Y(n556), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X4TS U428 (
	.A0(n75),
	.A1(n131),
	.B0(n130),
	.B1(FE_RN_1),
	.Y(n145), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1TS U429 (
	.A(FE_OFN17_weight_in_1),
	.B(FE_OFN260_data_in_4),
	.Y(n147), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX2TS U431 (
	.A(n135),
	.B(n134),
	.CI(n133),
	.S(n139),
	.CO(n138), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX2TS U432 (
	.A(n138),
	.B(n137),
	.CI(n136),
	.S(n193),
	.CO(n194), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U433 (
	.A(n556),
	.B(n563),
	.Y(n197), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX2TS U434 (
	.A(n141),
	.B(n140),
	.CI(n139),
	.S(n188),
	.CO(n192), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDHX2TS U435 (
	.A(tmp[5]),
	.B(n142),
	.S(n186),
	.CO(n133), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX4TS U437 (
	.A(n146),
	.B(n145),
	.CI(n144),
	.S(n184),
	.CO(n140), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U438 (
	.A(n188),
	.B(n187),
	.Y(n189), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U439 (
	.A(n189),
	.Y(n574), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX2TS U440 (
	.A(n186),
	.B(n185),
	.CI(n184),
	.S(n152), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X1TS U442 (
	.A0(FE_OFN258_FE_DBTN0_n34),
	.A1(n167),
	.B0(n147),
	.B1(FE_OFN149_weight_in_0),
	.Y(n176), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X1TS U444 (
	.A0(FE_OFN139_n226),
	.A1(FE_OFN251_weight_in_3),
	.B0(FE_OFN249_n156),
	.B1(n148),
	.Y(n169), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS U446 (
	.A(n574),
	.B(n97),
	.Y(n191), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U449 (
	.A(n153),
	.B(FE_OFN258_FE_DBTN0_n34),
	.Y(n154), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U450 (
	.A(n155),
	.B(n154),
	.Y(n6001), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS U451 (
	.AN(FE_OFN157_data_in_0),
	.B(FE_OFN149_weight_in_0),
	.Y(n605), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U452 (
	.A(tmp[0]),
	.B(n605),
	.Y(n606), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U453 (
	.A(n155),
	.B(n154),
	.Y(n601), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X2TS U454 (
	.A0(n6001),
	.A1(n606),
	.B0(n601),
	.Y(n597), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX2TS U455 (
	.AN(FE_OFN250_data_in_0),
	.B(FE_OFN131_n156),
	.Y(n171), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS U459 (
	.A(n161),
	.B(n160),
	.Y(n595), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1TS U461 (
	.A(FE_OFN245_data_in_0),
	.B(FE_OFN11_weight_in_3),
	.Y(n165), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X1TS U462 (
	.A0(FE_OFN139_n226),
	.A1(n165),
	.B0(n164),
	.B1(FE_OFN249_n156),
	.Y(n179), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X1TS U463 (
	.A0(FE_RN_11),
	.A1(n168),
	.B0(n167),
	.B1(FE_OFN149_weight_in_0),
	.Y(n178), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X4TS U465 (
	.A(n173),
	.B(n172),
	.Y(n588), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS U466 (
	.A(n173),
	.B(n172),
	.Y(n589), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX2TS U468 (
	.A(n176),
	.B(n175),
	.CI(n174),
	.S(n181),
	.CO(n5701), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX2TS U469 (
	.A(n179),
	.B(n178),
	.CI(n177),
	.S(n173),
	.CO(n182), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BX4TS U470 (
	.AN(n181),
	.B(n180),
	.Y(n583), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS U471 (
	.A(n181),
	.B(n182),
	.Y(n582), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS U472 (
	.A0(n584),
	.A1(n583),
	.B0(n183),
	.Y(n569), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX4TS U473 (
	.A(n186),
	.B(n185),
	.CI(n184),
	.S(n571),
	.CO(n187), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U474 (
	.A(n188),
	.B(n187),
	.Y(n573), 
	.VSS(VSS), 
	.VDD(VDD));
   OA21X4TS U475 (
	.A0(n189),
	.A1(n578),
	.B0(n573),
	.Y(n190), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS U477 (
	.A(n193),
	.B(n192),
	.Y(n565), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS U478 (
	.A(n195),
	.B(n194),
	.Y(n557), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X2TS U479 (
	.A0(n556),
	.A1(n565),
	.B0(n557),
	.Y(n196), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX4TS U480 (
	.A(n200),
	.B(n199),
	.CI(n198),
	.S(n213),
	.CO(n216), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX4TS U481 (
	.A(n203),
	.B(n202),
	.CI(n201),
	.S(n208),
	.CO(n215), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X4TS U484 (
	.A(FE_PSN281_n205),
	.B(tmp[8]),
	.Y(n221), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U485 (
	.A(FE_OCPN178_FE_OFN30_data_in_3),
	.B(FE_OFN142_weight_in_7),
	.Y(n223), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X4TS U486 (
	.A0(FE_OFN256_n279),
	.A1(n207),
	.B0(n223),
	.B1(FE_OFN168_n108),
	.Y(n217), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX4TS U487 (
	.A(n216),
	.B(n215),
	.CI(n214),
	.S(n230),
	.CO(n231), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX4TS U488 (
	.A(n219),
	.B(n218),
	.CI(n217),
	.S(n220),
	.CO(n235), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX4TS U489 (
	.A(FE_PSN287_n222),
	.B(n221),
	.CI(n220),
	.S(n214),
	.CO(n234), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U490 (
	.A(FE_OFN142_weight_in_7),
	.B(FE_OFN260_data_in_4),
	.Y(n237), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22X1TS U491 (
	.A0(FE_OFN256_n279),
	.A1(n223),
	.B0(FE_OFN168_n108),
	.B1(n237),
	.Y(n242), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U493 (
	.A(FE_OFN159_n),
	.B(FE_OFN25_data_in_6),
	.Y(n239), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS U495 (
	.A(n230),
	.B(FE_RN_6),
	.Y(n544), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS U496 (
	.A(n232),
	.B(n231),
	.Y(n546), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X4TS U501 (
	.A(n244),
	.B(n243),
	.Y(n532), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U502 (
	.A(n257),
	.B(n532),
	.Y(n245), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS U503 (
	.A(n246),
	.B(n245),
	.Y(n247), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX2TS U506 (
	.AN(n247),
	.B(FE_OFN100_FE_DBTN1_fire_in),
	.Y(N48), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX4TS U507 (
	.A(n250),
	.B(n249),
	.CI(n248),
	.S(n243),
	.CO(n259), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX4TS U510 (
	.A(n256),
	.B(FE_OCPN271_n255),
	.CI(n85),
	.S(n249),
	.CO(n265), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U511 (
	.A(n257),
	.B(n537),
	.Y(n262), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U512 (
	.A(n531),
	.B(n262),
	.Y(n264), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX4TS U513 (
	.A(n290),
	.Y(n534), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U514 (
	.A(n259),
	.B(n258),
	.Y(n538), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX3TS U515 (
	.A(FE_RN_8),
	.Y(n285), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1TS U516 (
	.A0(n260),
	.A1(n537),
	.B0(n285),
	.Y(n261), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFHX2TS U517 (
	.A(n267),
	.B(n266),
	.CI(n265),
	.S(n258),
	.CO(n271), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X4TS U520 (
	.A(n271),
	.B(n270),
	.Y(n284), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U521 (
	.A(n271),
	.B(n270),
	.Y(n282), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U522 (
	.A(n284),
	.B(n282),
	.Y(n272), 
	.VSS(VSS), 
	.VDD(VDD));
   CMPR32X2TS U525 (
	.A(n89),
	.B(n276),
	.C(n275),
	.S(n270),
	.CO(n296), 
	.VSS(VSS), 
	.VDD(VDD));
   CMPR32X2TS U526 (
	.A(tmp[14]),
	.B(tmp[13]),
	.C(n280),
	.S(n295),
	.CO(n298), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X4TS U527 (
	.A(n533),
	.B(n287),
	.Y(n289), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS U529 (
	.A0(n290),
	.A1(n289),
	.B0(n288),
	.Y(n291), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X4TS U530 (
	.A0(n293),
	.A1(n292),
	.B0(n291),
	.Y(n294), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS U531 (
	.A(n298),
	.B(n297),
	.Y(n367), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U532 (
	.A(n299),
	.B(tmp[15]),
	.Y(n462), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U533 (
	.A(n299),
	.B(tmp[15]),
	.Y(n461), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U534 (
	.A(n304),
	.B(n461),
	.Y(n300), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U537 (
	.A(n303),
	.Y(n368), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U538 (
	.A(n304),
	.B(n467),
	.Y(n447), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U539 (
	.A(n493),
	.B(n455),
	.Y(n313), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X2TS U540 (
	.A(n368),
	.B(n315),
	.Y(n318), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U542 (
	.A(n334),
	.B(n444),
	.Y(n423), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U543 (
	.A(n483),
	.B(n433),
	.Y(n328), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U544 (
	.A(n305),
	.B(tmp[16]),
	.Y(n466), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1TS U545 (
	.A0(n467),
	.A1(n307),
	.B0(n306),
	.Y(n448), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U546 (
	.A(n308),
	.B(tmp[17]),
	.Y(n492), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U547 (
	.A(n309),
	.B(tmp[18]),
	.Y(n454), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1TS U548 (
	.A0(n455),
	.A1(n311),
	.B0(n310),
	.Y(n312), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X2TS U549 (
	.A0(n316),
	.A1(n315),
	.B0(n314),
	.Y(n317), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U550 (
	.A(n319),
	.B(tmp[19]),
	.Y(n438), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U551 (
	.A(n320),
	.B(tmp[20]),
	.Y(n443), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1TS U552 (
	.A0(n444),
	.A1(n322),
	.B0(n321),
	.Y(n425), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U553 (
	.A(n323),
	.B(tmp[21]),
	.Y(n482), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U554 (
	.A(n324),
	.B(tmp[22]),
	.Y(n432), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1TS U555 (
	.A0(n433),
	.A1(n326),
	.B0(n325),
	.Y(n327), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X2TS U556 (
	.A0(FE_OCPN175_n294),
	.A1(n4101),
	.B0(n412),
	.Y(n332), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U557 (
	.A(n331),
	.B(tmp[23]),
	.Y(n413), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS U558 (
	.A(n332),
	.B(n86),
	.Y(n333), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U560 (
	.A(n333),
	.B(FE_OFN111_FE_DBTN1_fire_in),
	.Y(N61), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X2TS U561 (
	.A0(FE_RN_4),
	.A1(n424),
	.B0(n428),
	.Y(n335), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U564 (
	.A(n337),
	.B(n419),
	.Y(n391), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U565 (
	.A(n397),
	.B(n407),
	.Y(n347), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U566 (
	.A(n338),
	.B(n349),
	.Y(n382), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U567 (
	.A(n424),
	.B(n353),
	.Y(n371), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U568 (
	.A(n339),
	.B(tmp[24]),
	.Y(n418), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1TS U569 (
	.A0(n419),
	.A1(n341),
	.B0(n340),
	.Y(n392), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U570 (
	.A(n342),
	.B(tmp[25]),
	.Y(n401), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U571 (
	.A(n343),
	.B(tmp[26]),
	.Y(n406), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1TS U572 (
	.A0(n407),
	.A1(n345),
	.B0(n344),
	.Y(n346), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1TS U573 (
	.A0(n350),
	.A1(n349),
	.B0(n348),
	.Y(n381), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U574 (
	.A(n351),
	.B(tmp[27]),
	.Y(n386), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X2TS U575 (
	.A0(n428),
	.A1(n353),
	.B0(n352),
	.Y(n372), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U576 (
	.A(n354),
	.B(tmp[28]),
	.Y(n376), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X2TS U577 (
	.A0(n372),
	.A1(n375),
	.B0(n376),
	.Y(n4701), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U578 (
	.A(n355),
	.B(tmp[29]),
	.Y(n472), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X1TS U582 (
	.A(n360),
	.B(tmp[30]),
	.Y(n362), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U584 (
	.A(n364),
	.B(FE_OFN122_FE_DBTN1_fire_in),
	.Y(N68), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS U586 (
	.A(n369),
	.B(n95),
	.Y(n3701), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X4TS U587 (
	.A(n3701),
	.B(FE_OFN105_FE_DBTN1_fire_in),
	.Y(N52), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U592 (
	.A(n387),
	.B(n386),
	.Y(n388), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS U593 (
	.A(n389),
	.B(n388),
	.Y(n3901), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X4TS U594 (
	.A(n3901),
	.B(FE_OFN121_FE_DBTN1_fire_in),
	.Y(N65), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U595 (
	.A(n391),
	.Y(n394), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U596 (
	.A(n4101),
	.B(n394),
	.Y(n4001), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS U598 (
	.A(n398),
	.B(n90),
	.Y(n399), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U599 (
	.A(n399),
	.B(FE_OFN121_FE_DBTN1_fire_in),
	.Y(N63), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X2TS U600 (
	.A0(FE_OCPN174_n294),
	.A1(n405),
	.B0(n404),
	.Y(n408), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS U601 (
	.A(n408),
	.B(n91),
	.Y(n409), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U602 (
	.A(n409),
	.B(FE_OFN121_FE_DBTN1_fire_in),
	.Y(N64), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS U603 (
	.A0(FE_OFN163_n294),
	.A1(n417),
	.B0(n416),
	.Y(n4201), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U604 (
	.A(n422),
	.B(FE_OFN111_FE_DBTN1_fire_in),
	.Y(N62), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U605 (
	.A(n424),
	.B(n427),
	.Y(n478), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1TS U606 (
	.A0(n428),
	.A1(n427),
	.B0(n426),
	.Y(n479), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U612 (
	.A(n458),
	.B(n4501),
	.Y(n488), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1TS U613 (
	.A0(n4601),
	.A1(n4501),
	.B0(n449),
	.Y(n489), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS U618 (
	.A(n468),
	.B(n87),
	.Y(n469), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U619 (
	.A(n469),
	.B(FE_OFN106_FE_DBTN1_fire_in),
	.Y(N54), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U621 (
	.A(n473),
	.B(n472),
	.Y(n474), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X4TS U622 (
	.A(n475),
	.B(n474),
	.Y(n477), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X4TS U623 (
	.A(n477),
	.B(FE_OFN122_FE_DBTN1_fire_in),
	.Y(N67), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X4TS U624 (
	.A0(FE_OFN257_n294),
	.A1(n481),
	.B0(n4801),
	.Y(n485), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U625 (
	.A(n483),
	.B(n482),
	.Y(n484), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2X4TS U627 (
	.A(n495),
	.B(n494),
	.Y(n497), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X2TS U628 (
	.A(n497),
	.B(FE_OFN109_FE_DBTN1_fire_in),
	.Y(N55), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U667 (
	.A(n527),
	.B(n526),
	.Y(n528), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X2TS U668 (
	.A(FE_OFN257_n294),
	.B(n528),
	.Y(n5301), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1TS U669 (
	.A(n531),
	.B(n533),
	.Y(n536), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21X1TS U670 (
	.A0(n534),
	.A1(n533),
	.B0(n532),
	.Y(n535), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U672 (
	.A(n538),
	.B(n537),
	.Y(n539), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX1TS U674 (
	.A(n543),
	.Y(n551), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X2TS U675 (
	.A0(n553),
	.A1(n551),
	.B0(n5501),
	.Y(n549), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U677 (
	.A(n551),
	.B(FE_PSN286_n544),
	.Y(n552), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1TS U678 (
	.A(n553),
	.B(n552),
	.Y(n554), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS U679 (
	.AN(n554),
	.B(FE_OFN97_FE_DBTN1_fire_in),
	.Y(N46), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U680 (
	.A(FE_PSN280_n555),
	.Y(n567), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1TS U681 (
	.A(n5601),
	.B(n559),
	.Y(n562), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX2TS U682 (
	.AN(n562),
	.B(FE_OFN114_FE_DBTN1_fire_in),
	.Y(N45), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U683 (
	.A(FE_PSN285_n565),
	.B(n564),
	.Y(n566), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS U685 (
	.AN(n568),
	.B(FE_OFN114_FE_DBTN1_fire_in),
	.Y(N44), 
	.VSS(VSS), 
	.VDD(VDD));
   INVX2TS U686 (
	.A(n569),
	.Y(n579), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1TS U687 (
	.A0(n579),
	.A1(n97),
	.B0(n572),
	.Y(n576), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U688 (
	.A(n574),
	.B(FE_RN_5),
	.Y(n575), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS U689 (
	.AN(n577),
	.B(FE_OFN114_FE_DBTN1_fire_in),
	.Y(N43), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U690 (
	.A(n97),
	.B(n578),
	.Y(n5801), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1TS U691 (
	.A(n5801),
	.B(n579),
	.Y(n581), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS U692 (
	.AN(n581),
	.B(FE_OFN114_FE_DBTN1_fire_in),
	.Y(N42), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U693 (
	.A(n583),
	.B(n582),
	.Y(n585), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1TS U694 (
	.A(n585),
	.B(n584),
	.Y(n587), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS U695 (
	.AN(n587),
	.B(FE_OFN110_FE_DBTN1_fire_in),
	.Y(N41), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U696 (
	.A(n5901),
	.B(n589),
	.Y(n592), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS U698 (
	.AN(n594),
	.B(FE_OFN110_FE_DBTN1_fire_in),
	.Y(N40), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U699 (
	.A(n596),
	.B(n595),
	.Y(n598), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1TS U700 (
	.A(n598),
	.B(n597),
	.Y(n599), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS U701 (
	.AN(n599),
	.B(FE_OFN110_FE_DBTN1_fire_in),
	.Y(N39), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1TS U702 (
	.A(n602),
	.B(n601),
	.Y(n603), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS U703 (
	.AN(n604),
	.B(FE_OFN107_FE_DBTN1_fire_in),
	.Y(N38), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2X1TS U704 (
	.A(tmp[0]),
	.B(n605),
	.Y(n607), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2BX1TS U705 (
	.AN(n609),
	.B(FE_OFN103_FE_DBTN1_fire_in),
	.Y(N37), 
	.VSS(VSS), 
	.VDD(VDD));
endmodule

